### ISSUE TITLE
minimize option seems to disable generation of requires.

### ISSUE THREAD

**Issue by bdwain** [webpack-contrib/html-loader#107]
**Webpack version:**
1.14.0

**HTML-Loader version:**
0.4.4

**Please tell us about your environment:**
OSX Sierra

**Current behavior:**
I have this loader in my config
```js
{
  test: /index.*\.html$/,
  loaders: [
    'file-loader?name=[name].[ext]',
    'extract-loader',
    'html-loader?minimize=false&' + JSON.stringify({attrs: ['img:src', 'img:ng-src', 'object:data', 'link:href', 'a:href']})
  ]
}
```

and the file is not minimized, but it leaves tags unresolved, like this
`<link rel="shortcut icon" href="~img/favicon.ico">`. The files those reference are not pulled into the bundle.

If i remove the minimize=false, and leave the loader as 
```js
'html-loader?' + JSON.stringify({attrs: ['img:src', 'img:ng-src', 'object:data', 'link:href', 'a:href']
```
everything works as expected, but the index.html file is minified, which i do not want.

for reference, the favicon is at app/img/favicon.ico, and is loaded with this loader.
 ```js
  config.module.loaders.push({
    test: /favicon\.ico$/i,
    loader: 'file-loader?name=[path][name].[ext]&context=app/'
  });
```

**Expected/desired behavior:**
The link tag should end up being `<link rel="shortcut icon" href="img/favicon.ico">` and the favicon should be in the bundle.
 
* **Browser:** Chrom 55

**Comment by hemanth** [comment]
Thanks for reporting, this is fixed in #116.
