### ISSUE TITLE
Option to integrate with i8n plugin?

### ISSUE THREAD

**Issue by scottmas** [webpack-contrib/html-loader#11]
This isn't an issue, but really a feature request. I would love to use this loader in conjunction with the [internationalization plugin](https://github.com/webpack/webpack/tree/master/examples/i18n). The internationalization plugin is sweet, but it only works in Javascript and if any of you are like my company, almost all our textual content is written in the html, making the plugin essentially useless. However, if the html parser could be intelligent enough to look for i8n attributes (in the same way it looks for img src attributes), then this problem could be effectively solved.

Imagine a use scenario like so:

```
//An html file: someText.html
<div>
    <h1>Company Name</h1>
    <div i8n> Some text <b> with bold </b></div>
 </div>

//Then gets converted to this webpack module...
module.exports = "<div> <h1> Company Name </h1> <div i8n>" + __("Some text <b> with bold </b>") + "</div></div>"
```

I think this could work, although it would be very dependent on the implementation of the i8n plugin. There also might be some snags in ensuring the loader escapes special characters in the html and disallows nested i8n attributes. But in all, it might not be too bad assuming the i8n plugin plays nicely.

Would people be opposed to adding this feature?

**Comment by michael-ciniawsky** [comment]
@scottmas It's been a while, but are you still interested in implementing this ? I would like to discuss this further

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/html-loader/releases/tag/v1.0.0-alpha.0 (Template Functions)
