### ISSUE TITLE
npm install html-loader fails due to uglify-js dependency

### ISSUE THREAD

**Issue by joeheyming** [webpack-contrib/html-loader#115]
**Webpack version:**
n/a

**HTML-Loader version:**
latest

**Please tell us about your environment:**
OSX 10.12

**Current behavior:**
npm install html-loader fails on an empty node module with nothing inside node_modules

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "html-loader"
npm ERR! node v5.5.0
npm ERR! npm  v4.3.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: uglify-js@2.8.x
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.4.15, 2.4.7, 2.4.16, 2.4.6, 2.4.13, 2.4.9, 2.4.14, 2.4.8, 2.4.19, 2.4.17, 2.4.18, 2.4.11, 2.4.12, 2.4.10, 2.4.24, 2.7.5, 2.7.4, 2.7.3, 2.6.4, 2.4.20, 2.4.21, 2.4.22, 2.4.23, 1.3.1, 1.3.0, 1.3.3, 1.3.2, 1.3.5, 1.3.4, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0, 2.7.2, 2.7.1, 1.1.0, 2.3.1, 1.1.1, 2.3.2, 2.2.5, 2.2.4, 2.3.0, 1.0.2, 2.2.3, 2.3.5, 1.0.1, 2.2.2, 2.3.6, 2.2.1, 2.3.3, 2.2.0, 2.3.4, 1.0.6, 1.0.5, 2.5.0, 1.0.4, 1.0.3, 1.0.7, 1.2.3, 1.2.4, 1.2.1, 1.2.2, 0.0.1, 1.2.5, 0.0.3, 1.2.6, 0.0.2, 0.0.5, 2.4.4, 0.0.4, 2.4.5, 2.4.2, 2.4.3, 2.4.0, 1.2.0, 2.4.1

**Expected/desired behavior:**
npm install html-loader succeeds

**Comment by d3viant0ne** [comment]
@joeheyming - The problem is in `html-minifier` to be specific. `html-loader` is on the latest release for that lib.

See: https://github.com/kangax/html-minifier/blob/gh-pages/package.json#L64

I'll leave this open and work a resolution out with the upstream repo

**Comment by d3viant0ne** [comment]
@joeheyming - Also worth noting. Webpack 2.x does not support Node.js v5.5.0

`"node": ">=4.3.0 <5.0.0 || >=5.10"`

**Comment by joeheyming** [comment]
@d3viant0ne This happened to me on a blank project.

**Comment by joeheyming** [comment]
I don't see this issue anymore.  I'm closing the issue
