### ISSUE TITLE
interpolate dont work in webpack-dev-server

### ISSUE THREAD

**Issue by LancelotLewis** [webpack-contrib/html-loader#118]
when i use `interpolate` to insert another file, like: `${require('./header.html')}` , it's work well in `webpack` command, but when i use `webpak-dev-server`, `${require('./header.html')}` won't repalce to the content of `./header.html`

**Comment by michael-ciniawsky** [comment]
@LancelotLewis Still have this regressionO I need more info on your setup (`webpack.config.js`), it is likely related to pathing somewhere

**Comment by LancelotLewis** [comment]
@michael-ciniawsky I' m so sorry that i found it works when i use `webpack-dev-server`, the reason i faild before is i name the source file `index.html` and the build file `build.html`. So, when i run the code in `webpack-dev-server` mode, it's output the source file 'index.html' rather than build file 'build.html'.

Sorry to bothered you, it's my mistake. Your plugin is work well, if you need more detail about why i'm faild before, i'll try my best to help you. 

Best wishes!

**Comment by michael-ciniawsky** [comment]
As long as it was a config error and `html-loader` works as expected for you everthing fine 😛
