### ISSUE TITLE
Double quotes are removed from the html file after compilation.

### ISSUE THREAD

**Issue by diegoddox** [webpack-contrib/html-loader#119]
Not sure why but I'm using the `html-loader` with `html-webpack-plugin` and for some reason the double quotes from the `open graph` are removed from the `index.html` output.

`webpack -v 1.14.0`
`html-loader -v 0.4.5`
`html-webpack-plugin -v 2.28.0`

#### A sample of my webpack config.
`webpack.config.js`
```
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

let webpackBase = {
  target: 'web',
  entry: {
    'browser-entry': '/browser-entry.js'
  },
  output: {
    path: '/dist',
    filename: '[name].bundle.js',
    publicPath: '/'
  },
  module: {
    loaders: [{
        test: /\.js?$/,
        exclude: /node_modules/,
        loaders: ['babel']
      }]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: `!!html!./index.html`,
      hash: true,
      inject: 'body'
    })
  ]
};

module.exports = webpackBase;
```

#### And my index.html before compiled
`index.html`
```
<!DOCTYPE html>
<html>
<head>
  <meta property="og:title" content="" />
  <meta property="og:description" content="" />
</head>

<body>
  <div id="root"></div>
</body>
</html>
```

#### And after the compilation.

`dist/index.html`
```
<!DOCTYPE html>
<html>
<head>
  <meta property=og:title content="" />
  <meta property=og:description content="" />
</head>

<body>
  <div id="root"></div>
</body>
</html>
```

Note that all that has `og:` the double quote was removed, any idea why this is happening

**Comment by michael-ciniawsky** [comment]
@diegoddox It should work nevertheless, if I'm not mistaken `html-minifier` even removes the attribute quotes :). Does this occur without using `html-loader` aswell ?

**Comment by diegoddox** [comment]
Hi @michael-ciniawsky , no only when I use the `html-loader`,

**Comment by michael-ciniawsky** [comment]
Minifaction on somewhere e.g `webpack -p` ? Otherwise eventual bug in https://github.com/webpack-contrib/html-loader/blob/master/lib/attributesParser.js 😛 

But the HTML should work in the browser without quotes

**Comment by diegoddox** [comment]
True that, I don't have issues with the browser but facebook is not that happy with that :D

**Comment by michael-ciniawsky** [comment]
I will look into it when I have time 🙃 , is using `html-loader` mandatory for you atm? Otherwise please just remove it meanwhile 😛

**Comment by diegoddox** [comment]
Thanks @michael-ciniawsky no stress, I have fixed manually the `index.html` output at the moment.

**Comment by charlesyclim** [comment]
If you do not mind html-loader being executed without the htmlMinifier, you can solved it by manually editing the html-loader code:
@line119 in index.js, comment out that statement:
//		content = htmlMinifier.minify(content, minimizeOptions);
Then it will work perfectly.

**Comment by diegoddox** [comment]
Thanks @charlesyclim

**Comment by wavelynn** [comment]
HtmlWebpackPlugin has choice `minify` option to control if to remove quotes.

**Comment by TylerTemp** [comment]
> HtmlWebpackPlugin has choice `minify` option to control if to remove quotes.

For ppl who need to Google how to change this `minify` option, here is an example:

```javascript
new HtmlWebpackPlugin({
    template: 'src/index.html',
    minify: {
        collapseInlineTagWhitespace: true,
        collapseWhitespace: true,
        preserveLineBreaks: true,
        minifyURLs: true,
        removeComments: true,
        removeAttributeQuotes: false  // <- here is the magic
    }
})
```

**Comment by safrazik** [comment]
If you're using `html-loader` you can use the `minimize` option. By default, the value is `true` for production mode and `false` otherwise. https://webpack.js.org/loaders/html-loader/#minimize

```javascript
module.exports = {
    module: {
      rules: [
        // ...
        {
          test: /\.html$/i,
          loader: 'html-loader',
          options: {
            minimize: {
              removeComments: true,
              collapseWhitespace: true,
            },
          },
          // ...
        },
}
```
