### ISSUE TITLE
feat: support exporting a template function

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack-contrib/html-loader#120]
**I'm submitting a feature request**

#### Template (`{Function}`)

**component.html**
```html
<div>${ _.hello }<div>
```

**webpack.config.js**
```js
{
  loader: 'html-loader', options: { template: true }
}
```

**component.js**
```js
import template from './component.html'

const component = template({ hello: 'Hello World!' })
// <div>Hello World!</div>
```

**Comment by bobossy** [comment]
This feature should be very convenient, but it hasn't been merge to the release version after half year

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/html-loader/releases/tag/v1.0.0-alpha.0

**Comment by denis-migdal** [comment]
Alternatively, I created a loader that might do something close to what you want to achieve:
https://github.com/denis-migdal/prehtml-loader

Else, by disabling interpolation, you could also use template-string-loader:
https://github.com/bradbenvenuti/template-string-loader
