### ISSUE TITLE
HTML appears <error after compilation

### ISSUE THREAD

**Issue by yin466739523** [webpack-contrib/html-loader#125]
a.html 

<div>
    aaaa < aaaa
</div>

~~~~~~~~~~~~~~~~~~~~~~~~~~
<div>
 ${require('homt/a.html')}
</div>

ERROR in Error : pages Error : < aaa

**Comment by madflow** [comment]
This is due the ```html-minifier``` dependency.

See: https://github.com/kangax/html-minifier/issues/712

The upstream issue was closed arguing  that ```aaaa < aaaa``` is not valid HTML.

**Comment by extensionsapp** [comment]
In this case, I would like to get the original line `aaaa < aaaa` at the output instead of the error.
