### ISSUE TITLE
html-loader

### ISSUE THREAD

**Issue by mugu9** [webpack-contrib/html-loader#127]
Could you tell what's the correct path about file.html about html-loader in webpack2? I'm so tangled to use the html-loader. I just want to deal with img or png in template html.

**Comment by bsalex** [comment]
Hi. Sorry, but it is not clear what is the problem you have.
Recently I've worked on a simple webpack boilerplate for my team. I beleive it might help you.

Take a look at the rule here: 
https://github.com/bsalex/typescript-boilerplate/blob/master/build/webpack.config.dev.js#L21

And here is how it is used in typescript (it should be the same for js):
https://github.com/bsalex/typescript-boilerplate/blob/master/src/components/SomeComponentFromHtml/SomeComponentFromHtml.ts#L2
The html template contains an image `./sample.jpg`
