### ISSUE TITLE
Resolve inline css in html

### ISSUE THREAD

**Issue by var-bp** [webpack-contrib/html-loader#131]
Hello, is there any technique to resolve inline css in html using this loader? This is a very in-demand need.
```
// webpack.config.js
const HtmlWebpackPlugin = require('html-webpack-plugin');
const config = {
  module: {
    rules: [
      {
        test: /\.html$/,
        use: 'html-loader'
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'src/index.html'
    })
  ]
};
```
```
// src/index.html
<div style="background: url('assets/image.jpg');"></div>
```

**Comment by OzzieOrca** [comment]
Using the [`interpolate `](https://stackoverflow.com/questions/44096749/webpack-load-images-from-inline-style-background-image) flag and using `require` in your HTML is a solution but makes your templates uglier. See: https://stackoverflow.com/questions/44096749/webpack-load-images-from-inline-style-background-image

I wish it would do this natively.

**Comment by michael-ciniawsky** [comment]
posthtml-loader + posthtml-postcss
