### ISSUE TITLE
Regex support for pattern attribute

### ISSUE THREAD

**Issue by baidario** [webpack-contrib/html-loader#132]
**I'm submitting a bug report**

**Webpack version:** 3.0.0
**HTML-Loader version:** 0.4.5
**Please tell us about your environment:** Windows 10

**Current behavior:**
I use angularjs, and some inputs has `ng-pattern` attribute. html-loader remove backslashes in regex inside this attribute and because of this regex not valid.
In my code I have `ng-pattern="/^\+[\d]{7,15}$/"` and output is 

![](https://image.prntscr.com/image/VDoMM3RBTHq3POFlkq6ZPA.png)

**Expected/desired behavior:**
Please, add regex processing

**Loader config**
```
{
  test: /\.html$/, 
  use: [
    {
      loader: 'html-loader',
      options: {
        minimize: true,
        removeComments: true,
        collapseWhitespace: true,
        interpolate: true
      }
    }
  ]
}
```

* **Browser:** Chrome 59
 
* **Language:** ES5

**Comment by michael-ciniawsky** [comment]
Does this also happen without `minimize: true`? It's likely related to `html-minifier`

**Comment by baidario** [comment]
This behavior not depend on `minimize` option

**Comment by jinker** [comment]
Is the `interpolate: true` option

**Comment by jinker** [comment]
The pr #153  solve the problem
