### ISSUE TITLE
`htmlLoader` property not allowed in webpack >= v2.0.0 configs 

### ISSUE THREAD

**Issue by nevcos** [webpack-contrib/html-loader#135]
**I'm submitting a bug report**

**Webpack version:**
3.3.0

**HTML-Loader version:**
0.4.5

**Please tell us about your environment:**
Windows 10 + Node 6.11.0 + NPM 5.3.0

**Current behavior:**
Using `htmlLoader` property as described on [docs](https://github.com/webpack-contrib/html-loader#advanced-options) give the following error when calling webpack:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'htmlLoader'. These properties are valid:
```

**Expected/desired behavior:**
Because webpack no longer accepts properties not from webpack schema, the docs should be updated to use `webpack.LoaderOptionsPlugin`:

```
plugins: [
  new webpack.LoaderOptionsPlugin({
    options: {
      htmlLoader: {
       minimize: true
      }
    }
  })
]
````

More information here: https://stackoverflow.com/a/43135993/198787

**Comment by michael-ciniawsky** [comment]
This will likely be removed in #134 (`v1.0.0`) and `options.minimize` will work this way then 

```js
{
   test: /\.html$/,
   use: { 
     loader: 'html-loader', 
     options: { minimize: {...options} }
  }
}
```
Meanwhile the usage of `LoaderOptionsPlugin` is the correct way, but it's usage is discouraged as it was mainly meant as a migration path between webpack v1 => webpack v2 in the early days of webpack v2 :)

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/html-loader/releases/tag/v1.0.0-alpha.0 (removed)
