### ISSUE TITLE
HTML imports

### ISSUE THREAD

**Issue by jhnns** [webpack-contrib/html-loader#14]
Are there any plans or ideas how to support [html-imports](http://www.html5rocks.com/en/tutorials/webcomponents/imports/)?

I guess this would also require to tackle the problem how to include referenced scripts and stylesheets into the bundle.

**Comment by chrisnicola** [comment]
Definitely agree there should be support for scripts and stylesheets, as there already is for images.

This might be a job for the HtmlWebpackPlugin though.

**Comment by B3nCr** [comment]
Hi, is this still alive? Is there another way to handle html imports? 
Thanks Ben

**Comment by jhnns** [comment]
I don't think so. Since work on the specification has been paused, I don't think it's worth to invest more time on this currently.

**Comment by Odaeus** [comment]
@jhnns I didn't know the spec for HTML Imports is not progressing any more, do you have any more information on this?

**Comment by jhnns** [comment]
Mozilla and Microsoft have paused development on HTML imports until the [ES loader spec](https://github.com/whatwg/loader) has been finished, because they see too much overlap between them (see [here](http://www.2ality.com/2015/08/web-component-status.html) and [here](https://hacks.mozilla.org/2015/06/the-state-of-web-components/))

**Comment by B3nCr** [comment]
Even if the specification has been paused there are still a tonne of components out there that already use it.

I'm trying to work out a way of using some of the pre-canned Polymer elements and I don't think the polymer-loader is going to work as it seems to be for creating brand new components.

https://elements.polymer-project.org/

I can't see a way of using these without separately including them in my main page.

**Comment by jhnns** [comment]
Does the [vulcanize-loader](https://github.com/aitoroses/vulcanize-loader) solve your use-case?

This is very subjective, but personally I'm not convinced by HTML imports. They just import everything in the global namespace with all the namespace issues etc. I think, ES2015 imports are way more powerful since they are statically analyzable by tools. Thus we could use tree-shaking for HTML and CSS for instance.

**Comment by aruntk** [comment]
@B3nCr Here is a loader I made to handle webcomponents imports. https://github.com/aruntk/link-loader.

Complete Webcomponents-loader - https://github.com/aruntk/wc-loader

**Comment by michael-ciniawsky** [comment]
Since the html-imports spec is likely to be dropped in favour of the es-loader spec and alternatives `link-loader/wc-loader`  are available for webpack I'm closing this for the moment. Should there be any changes feel free to reopen
