### ISSUE TITLE
wrong URLs [object Object] with file-loader@1

### ISSUE THREAD

**Issue by andrenarchy** [webpack-contrib/html-loader#140]
**I'm submitting a bug report**

**Webpack version:**
3.4.1

**HTML-Loader version:**
0.5.0

**Please tell us about your environment:**
Linux

**Current behavior:**
When used with file-loader@1 it creates HTML like `<img src="[object Object]">` from `<img src="img/logo.png">`.

**Expected/desired behavior:**
It should insert the path of the file that `file-loader` created, e.g., `<img src="img/logo.a1f96acab.png">`.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

This is the relevant part of the webpack config:
```javascript
{
  // ...
  module: {
    rules: [
      {
        test: /\.html$/,
        use: [{
          loader: 'html-loader',
          options: {interpolate: 'require'}, // allow ${require(...)} in html
        }],
      },
      {
        test: /\.(jpg|png|svg)$/,
        use: [
          {
            loader: 'file-loader',
            options: {name: '[path][name].[md5:hash:hex:8].[ext]'},
          },
          {
            loader: 'image-webpack-loader',
            options: {},
          },
        ],
      },
      // ...
    ]
  }
}
```

The returned object from file-loader looks like `{default: 'img/logo.a1f96acab.png'}` and file-loader@1 switched to es6 default imports so it looks like this issue is similar to the css-loader problem reported in https://github.com/webpack-contrib/file-loader/issues/181.

**Comment by michael-ciniawsky** [comment]
The best solution for now is to pin `file-loader` at `v0.11.2`. We oversaw that exporting an ES2015 Module in `v1.0.0` causes problems with `html-loader, css-loader`'s asset resolving which uses `require('path/to/asset')` and doesn't work with an ES2015 export yet => `require('path/to/asset').default`.

**Comment by cyberhck** [comment]
how's this closed? in which commit? what's the solution for now?
