### ISSUE TITLE
Example section in README.md

### ISSUE THREAD

**Issue by gswcm** [webpack-contrib/html-loader#144]
**I'm submitting a bug report**
The Example section addresses `{ test: /\.jpg$/, use: [ "file-loader" ] },` as a part of configuration file, but later on in a few places, e.g. `<img src="image.png" data-src="image2x.png" >` reference `image.png` is handles as it was `image.jpg`

For example:
```
require("html-loader!./file.html");

// => '<img src="http://cdn.example.com/49eba9f/a992ca.png"
//         data-src="image2x.png">'

```
appears to be **incorrect** as with the current configuration PNG files are handled by `url-loader`, not by `file-loader`

**Current behavior:**
See above, in the description of the problem.

**Expected/desired behavior:**
The expected correction would replace `image.png` by `image.jpg` in all `<img ...>` tags.

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/html-loader/releases/tag/v1.0.0-alpha.0 README on the `next` branch
