### ISSUE TITLE
[v0.5.5] Root option doesn't work with interpolate

### ISSUE THREAD

**Issue by steelstring94** [webpack-contrib/html-loader#149]
**I'm submitting a bug report**

**Webpack version:**
2.x

**HTML-Loader version:**
^0.5.1

**Please tell us about your environment:**
Linux (Ubuntu 17.04 MATE 64-bit)

**Current behavior:**
With the `root` option of `html-loader` set to `/public`, and an HTML file at `/views/index.html`, normal images, as in `<img src="images/img.png">` will be loaded appropriately from `../public/images/image.png`.  However, if the interpolate option is set to true, and you have something like `<div style="background-image: url('${require(`images/img.png`)}');"></div>`, then you will get an error.  The inline image must be referred to as `../public/images/img.png`

**Expected/desired behavior:**
Parse inline interpolated `${require()}` syntax as expected and factor in the `root` option when resolving the path.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

Use `html-loader` with `extract-loader` and `file-loader` to parse HTML.  Set `interpolate` to true for `html-loader`.  Include a background image inline with the CSS `url()` property and appropriate `${require()}` syntax within a `style` attribute, referencing the path with the assumption that the `root` will be prepended, as with a normal `img` tag.  This will not work, and you will get an error.

* **What is the expected behavior?**
Same as the answer to this same question above.

* **What is the motivation / use case for changing the behavior?**
Easily inline background-images, especially for parallax scrolling, without having to use a special syntax for their path.
 
* **Browser:** all 
* **Language:** all

**Comment by samuelsiau** [comment]
Any solution? any one?

**Comment by evilebottnawi** [comment]
Works fine, can't reproduce, if still have problems please open new issue with reproducible test repo, thanks
