### ISSUE TITLE
How can I get a html text by require()

### ISSUE THREAD

**Issue by xiaogan18** [webpack-contrib/html-loader#156]
the code:
var rr=require('html-loader?./1.html')
       console.info(rr)
       console.info(typeof(rr))
console log:
export default "<div> <div>testing</div> </div>";
string

I want get a html string of 1.html,like"<div> <div>testing</div> </div>" without "export default".

**Comment by michael-ciniawsky** [comment]
```js
const html = require('html-loader?./1.html').default
```

**Comment by xiaogan18** [comment]
it output  'undefined'

**Comment by michael-ciniawsky** [comment]
Try `!` instead of `?` in the file path please

```js
const html = require('html-loader!./1.html) // should normally work
const html = require('html-loader!./1.html').default
```

Otherwise show your full `webpack.config.js`

**Comment by xiaogan18** [comment]
`'use strict'
const path = require('path')
const utils = require('./utils')
const config = require('../config')
const vueLoaderConfig = require('./vue-loader.conf')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

const createLintingRule = () => ({
  test: /\.(js|vue)$/,
  loader: 'eslint-loader',
  enforce: 'pre',
  include: [resolve('src'), resolve('test')],
  options: {
    formatter: require('eslint-friendly-formatter'),
    emitWarning: !config.dev.showEslintErrorsInOverlay
  }
})

module.exports = {
  context: path.resolve(__dirname, '../'),
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
    }
  },
  module: {
    rules: [
      ...(config.dev.useEslint ? [createLintingRule()] : []),
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.html$/,
        loader: 'html-loader',
        options: {
          minimize:true
        }
      }
    ]
  },
  node: {
    // prevent webpack from injecting useless setImmediate polyfill because Vue
    // source contains it (although only uses it if it's native).
    setImmediate: false,
    // prevent webpack from injecting mocks to Node native modules
    // that does not make sense for the client
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty'
  }
}
`

**Comment by michael-ciniawsky** [comment]
Did you remove the `html-loader!` prefix from the import/require when setting `html-loader` in `webpack.config.js` ?  This might also be related to `vue` && `vue-loader`  which loads HTML on it's own  => `vue-html-loader`, so please consider opening an issue in `vue-loader` instead aswell
