### ISSUE TITLE
[v1.0.0-alpha (Feature)] support explicit `{ tag: 'attr' }` patterns for URL resolving (`options.url`)

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack-contrib/html-loader#159]
### `Feature`

The current asset resolving (`<img src="path/to/file.png">`) is likely _too_ aggressive for real projects and doesn't match custom attribute names like `<tag custom-src>` atm. 

> ℹ️  The [option] design/interface still needs triage and any feedback/ideas on this are highly welcome and appreciated

**webpack.config.js**
```js
{
   loader: 'html-loader'
   options: {
       url:  { tag: 'attr' } && { tag: [ 'attr', 'attr' ] }
   }
}
```

**Comment by benjaminpreiss** [comment]
How was this feature implemented?
As far as I understand this is about custom attributes, like for example:

```js
<video
    poster="../img/example.jpg">
</video>
```
I there a part in the doc that references this?
