### ISSUE TITLE
Error nesting interpolation

### ISSUE THREAD

**Issue by controversial** [webpack-contrib/html-loader#170]
**Current behavior:**
When one file (`1.html`) requires another (`2.html`) using the interpolation syntax:
```jsx
...
${require('!html-loader?interpolate!./2.html')}
...
```
and then *that* file itself (`2.html`) requires another HTML file (`3.html`):
```jsx
<div>
  ${require('!raw-loader!./3.html')}
</div>
```
the `require()` call in `2.html` throws an error:
```
ReferenceError: require is not defined
    at !html-loader?interpolate!./2.html:1:1
    at Script.runInContext (vm.js:74:29)
    at Script.runInNewContext (vm.js:80:15)
```
**Expected/desired behavior:**
`1.html` should include the contents of `2.html`, with the contents of `3.html` substituted in the place where it is required in `2.html`.

**What is the motivation / use case for changing the behavior?**
This would allow more complex file arrangements with `html-loader`
 
**Browser:** all 
**Language:**  ES6
**Webpack version:** 3.8.1
**HTML-Loader version:** 0.5.1
**Please tell us about your environment:** macOS 10.13.3, node v9.4.0

**Comment by controversial** [comment]
If, in `2.html`, the file for which `require` is undefined in interpolation, I do something like 
```
${Object.keys(this)}
```
it appears that the only things defined in `2.html`'s execution context are `module` (assigned to`{}`) and `__webpack_public_path__` (assigned to `"/"`). The context in which `1.html` is executed provides `require` and `exports` as additional global variables, which allows it to require other files, but `2.html` is not provided with these same capabilities when it's being executed

**Comment by evilebottnawi** [comment]
Sorry, but the `interpolate` option was removed without replacement, please consider on migration template system and relevant loader, I will provide simple templating without extra logic in examples in near future
