### ISSUE TITLE
Use the mode option of Webpack 4

### ISSUE THREAD

**Issue by blacksonic** [webpack-contrib/html-loader#172]
**I'm submitting a feature request**

**Webpack version:**
4.2.0

**HTML-Loader version:**
0.5.5

**Please tell us about your environment:**
Linux

**Current behavior:**
When bundling the application with `mode: production` the HTML fragments stay unminified.
I have to add the LoaderOptionsPlugin to get minification.
```
plugins: [
  new webpack.LoaderOptionsPlugin({
    minimize: true
  })
],
```

**Expected/desired behavior:**
The loader should check the mode of Webpack and enable minifications in production mode.

* **What is the motivation / use case for changing the behavior?**
It is now misleading for anyone expecting production mode in Webpack 4.

**Comment by thw0rted** [comment]
IMHO minification is too dangerous to turn on by default, even in production mode, and the benefits are minimal compared to the risks.  Javascript will (usually) save far more space by minifying, percentage-wise.

**Comment by thw0rted** [comment]
Upon reflection, my real concern might just be that the default minimization options are too aggressive -- for example, I use html-loader to feed templates to Angular, which will always break if caseSensitive is not enabled (off by default), and will break in certain cases when removeAttributeQuotes is enabled (same).  Maybe a more conservative set of minimization defaults would make sense, but as it ships today, enabling it for every production build would cause more harm than good.

**Comment by McGiogen** [comment]
I think that pure HTML is minificable without problems. Enabling minification as default will be an issue only if some specific frameworks are used, and the developers using them will change some specifical options in their config (as they do now). But this is normality.
In a project we have AngularJS and js now is automatically minified. Our problem with it is that function names are "renamed", broking our controllers. We simply use `keep_fnames: true`, changing the default configuration as everyone in the world.
The HTML situation with auto-minification in production is the same.

**Comment by evilebottnawi** [comment]
Done in master, we use only safe minification actions so it is safe in production, anyway if you have some problems feel free to open new issues, thanks
