### ISSUE TITLE
html-loader is not working  with react and electron

### ISSUE THREAD

**Issue by EmanuelaGr** [webpack-contrib/html-loader#173]
Hi, 

I have this error after I build an electron app both in production and development mode. On my browser is working, but after I build I get this error. 

     

```
Uncaught Error: Module parse failed: Unexpected token (1:0) You may
     need an appropriate loader to handle this file type. 
| <!DOCTYPE html> | <html> | <head>

```

I'm loading my file like this:

```
getHTMLFile(partNumber) {
    let html = require(`../Partlists/${partNumber}.html`);
    return {__html: `<div>${html}</div>`};
  }

<div dangerouslySetInnerHTML={this.getHTMLFile(this.state.selectedPartNumber)}></div>
```
and I added html on my webpack files like in here: 
https://stackoverflow.com/questions/40108843/react-how-to-load-and-render-external-html-file/46997182#46997182

Any suggestions?

**Comment by evilebottnawi** [comment]
You need `html-loader`, sorry i can't help without configuration, feel free to open new issue with reproducible test repo or example of config, sorry for delay
