### ISSUE TITLE
Outdated README.md doc

### ISSUE THREAD

**Issue by leandrw** [webpack-contrib/html-loader#177]
**I'm submitting a bug report**
When I use proposed way to pass advanced options as suggested here:
```javascript
var path = require('path')

module.exports = {
  ...
  module: {
    rules: [
      {
        test: /\.html$/,
        use: [ "html-loader" ]
      }
    ]
  },
  htmlLoader: {
    ignoreCustomFragments: [/\{\{.*?}}/],
    root: path.resolve(__dirname, 'assets'),
    attrs: ['img:src', 'link:href']
  }
};
```

I get the error described in **current behaviour**
I think this part of doc is outdated, for webpack v1 only, broken from v2+.

**Webpack version:**
3.x

**HTML-Loader version:**
0.5.x

**Please tell us about your environment:**
Linux

**Current behavior:**
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'htmlLoader'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?,entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           htmlLoader: ...
         }
```

**Expected/desired behavior:**
Compile success

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
Pass options to the loader as proposed in advanced options section. 

* **What is the expected behavior?**
Describe an updated way to pass advanced options to the html-loader (through `options`?)

* **What is the motivation / use case for changing the behavior?**
Make developers life better
 
* **Browser:** all
 
* **Language:** all

**Comment by leandrw** [comment]
I solved the problem here by using `options` property to pass `root` option:
```javascript
{
    test: /\.html$/,
    use: [{
    loader: 'html-loader',
    options: {
         minimize: false,
         root: path.resolve(__dirname, './templates')
       }
   }]
},
```

**Comment by evilebottnawi** [comment]
Docs were refactor in master, thanks for the issue
