### ISSUE TITLE
about html-minifier

### ISSUE THREAD

**Issue by ZSkycat** [webpack-contrib/html-loader#179]
**Webpack version:**
4.16.5

**HTML-Loader version:**
0.5.5

**Please tell us about your environment:**
Windows 10

### options is invalid
removeCommentsFromCDATA
removeCDATASectionsFromCDATA
removeStyleTypeAttributes
https://github.com/webpack-contrib/html-loader/blob/951541080733503e68f103ae72ce58d32e370a8e/index.js#L109

### unsafe optimizations
useShortDoctype
http://perfectionkills.com/experimenting-with-html-minifier/#use_short_doctype

---

Propose to cancel the default configuration, consistent with html-minifier. Or allow the default configuration to be turned off.
Because in order to be consistent, I have to override the default values.

```js
function createHtmlLoaderOptions(config) {
    return {
        attrs: [],
        interpolate: true,
        minimize: true,
        removeCommentsFromCDATA: null,
        removeCDATASectionsFromCDATA: null,
        removeStyleTypeAttributes: null,
        collapseWhitespace: false,
        conservativeCollapse: false,
        keepClosingSlash: false,
        minifyCSS: false,
        minifyJS: false,
        removeAttributeQuotes: false,
        removeComments: false,
        removeScriptTypeAttributes: false,
        useShortDoctype: false,
        ...config,
    };
}
```

**Comment by evilebottnawi** [comment]
> removeCommentsFromCDATA
> removeCDATASectionsFromCDATA
> removeStyleTypeAttributes

Fixed in master

> Because in order to be consistent, I have to override the default values. 

Fixed in master

html 4.01 is deprecated so `useShortDoctype` is safe
