### ISSUE TITLE
trying to use html-loader

### ISSUE THREAD

**Issue by FrancisVilaAxway** [webpack-contrib/html-loader#181]
**I'm submitting a bug report (as invited to do so by Hemanth H.M) **

**Webpack version:** could not find this information. I found a page explaining how to find this in  https://www.fullstackreact.com/p/using-webpack-with-create-react-app/ that describes the create-react-app, but the directory structure appears to be completely different.

**HTML-Loader version:**: "^0.5.5"

**Please tell us about your environment:**
Windows 10

**Current behavior:**

I’m using reactjs with create-react-app and I’m trying to import static html files into a help panel. I want to import html without modifying it, so that I can update the html files with content generated by an html editor (such as Confluence).
 
I’m trying to use html-loader but with the syntax indicated in the README on https://github.com/webpack-contrib/html-loader , I get an error message.:
`Unexpected '!' in 'html-loader!./toto.html'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax`

**Expected/desired behavior:**

I want to see the html content of the file toto.html in the div with id="container" 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
Excuse my ignorance. I don't know how to do a gist/jsbin of my webpack configuration.

Here’s what’s written in the documentation:
```
require("html-loader!./file.html");
// => '<img src="http://cdn.example.com/49eba9f/a992ca.png"
//         data-src="image2x.png">'
```
Here’s what I wrote:
`const html = require("html-loader!./toto.html");`
Here’s the error message:
`Unexpected '!' in 'html-loader!./toto.html'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax`

I tried replacing the “!” with a “?”, but got  Error: Cannot find module "."

For the moment I’m using the simplest create-react-app project with just the call to html-loader. I haven’t defined any routes in the react sense.
This is what the **App.js** file looks like. I put the changes I made in bold (** ** - seems it doesn't work inside code?).
 
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
 
class App extends Component {
  render() {
    **const html = require("html-loader!/toto.html");**
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        **<div id="container" dangerouslySetInnerHTML={ html } />**
      </div>
    );
  }
}
export default App;
```

Here's what I pasted into webpack.config.js:

```
  {
  modules: {
	loaders: [
	  { test: /\.html$/, loader: 'html' }
	]
  }
}
```

* **Browser:** [ Firefox 61 ] 
 
* **Language:** [ES6 (in create-react-app)] 

File package.json:
```
{
  "name": "help_in_product",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/react-native": "^0.56.11",
    "axios": "^0.18.0",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-native": "^0.56.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "html-loader": "^0.5.5"
  }
}
```

**Comment by michael-ciniawsky** [comment]
> Unexpected '!' in 'html-loader!./toto.html'. Do not use import syntax to configure webpack loaders import/no-webpack-loader-syntax

That's seems to be a linter warning ? But since you already have the `html-loader` in ypur `webpack.config.js` it is not necessary to use `html-loader!` prefix, juts use 

```diff
import React, { Component } from 'react';
import logo from './logo.svg';
+ import html from './toto.html;
import './App.css';
 
class App extends Component {
  render() {
-   const html = require("html-loader!/toto.html");
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        **<div id="container" dangerouslySetInnerHTML={ html } />**
      </div>
    );
  }
}

export default App;
```

and it should work :)

**Comment by ar-IGT** [comment]
What if I don't want to interpolate imported html, but inject it into script as a string?
What I'd like to achieve, is to bundle all of available scripts and html files into one single .js script.
How to use html-loader to do that?
