### ISSUE TITLE
Use `interpolate flag` to be deleted by `html-minifier`

### ISSUE THREAD

**Issue by ZSkycat** [webpack-contrib/html-loader#182]
**I'm submitting a bug report**

**Webpack version:**
4.17.1

**HTML-Loader version:**
0.5.5

**Please tell us about your environment:**
Windows 10

Sample file: 
```html
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="UTF-8">
    <title>${require('src/config/base').appName}</title>
    <style class="before-app">${require('src/style/app-html.inline.scss')}</style>
</head>

<body>
    <div id="app"></div>
    <div class="before-app"></div>
</body>

</html>
```

**Current behavior:**
```html
<!DOCTYPE html><html lang=zh><head><meta charset=UTF-8><title>${require('src/config/base').appName}</title><style class=before-app>*,:after,:before{box-sizing:border-box}......</style></head><body><div id=app></div><div class=before-app></div></body></html>
```

**Expected/desired behavior:**
```html
<!DOCTYPE html><html lang=zh><head><meta charset=UTF-8><title>${require('src/config/base').appName}</title><style class=before-app></style></head><body><div id=app></div><div class=before-app></div></body></html>
```

`interpolate flag` is executed after `html-minifier`. When `minifyCSS` is enabled, the wrong text will be deleted.
https://github.com/webpack-contrib/html-loader/blob/master/index.js#L106-L129

The solution is to add `ignoreCustomFragments: [/\$\{require.*\}/],`, which ignores `Template literals`
(https://github.com/kangax/html-minifier#options-quick-reference)

**Comment by anikethsaha** [comment]
Right how interpolate is done after minification which seems that this issue has been solved 

cc @evilebottnawi ?

**Comment by evilebottnawi** [comment]
Yes, but we need to add tests

**Comment by anikethsaha** [comment]
> Yes, but we need to add tests

coool, I will try to add them soon

**Comment by evilebottnawi** [comment]
Sorry, but the `interpolate` option was removed without replacement, please consider on migration template system and relevant loader, I will provide simple templating without extra logic in examples in near future
