### ISSUE TITLE
Pass parameters to imported partials

### ISSUE THREAD

**Issue by entozoon** [webpack-contrib/html-loader#184]
Not sure if feature request, or currently possible (https://github.com/webpack-contrib/html-loader/issues/120 ?), but it'd be mad useful.

Using `1.0.0-alpha.0`

parent.html
```
<import src="./component.html" foo="bar"></import>
```

component.html
```
<div> ${foo} </div>
```

**Comment by entozoon** [comment]
Really? I mean, I don't want to use polymer or JS at all ideally. My use case is building a set of html templates rather than an app. (But later built into one)

**Comment by orangecoloured** [comment]
Would be great to see this feature implemented. I'm migrating a project from gulp to webpack and there's the `gulp-file-include` plugin that can inject params into partials.

**Comment by evilebottnawi** [comment]
HTML doesn't support variable you need loader for templates depending what template language you are use

**Comment by orangecoloured** [comment]
@evilebottnawi I'm using html language. I have a number of html files that should share the same meta tags, but should have different titles and sometimes description.

**Comment by evilebottnawi** [comment]
@orangecoloured Feel free to send a PR

**Comment by entozoon** [comment]
A direct replacement with https://github.com/pcardune/handlebars-loader/ did the trick for my use-case, in the meantime.

**Comment by orangecoloured** [comment]
I ended up using ejs.

**Comment by denis-migdal** [comment]
I am flooding a little, but I created a loader that might do the trick:
https://github.com/denis-migdal/prehtml-loader

**Comment by evilebottnawi** [comment]
The `import` feature was removed from official html specifications so we don't want to support it, next major release will be without `import` support , feel free to leave feedback,
