### ISSUE TITLE
Files in `srcset` are not loaded.

### ISSUE THREAD

**Issue by siakaramalegos** [webpack-contrib/html-loader#188]
**I'm submitting a bug report**
**I'm submitting a feature request**

I feel like this is a bug since `srcset` is valid HTML, but I kept both bug and feature request depending on how you want to handle it.

**Webpack version:**
4.20.2

**HTML-Loader version:**
0.5.5

**Please tell us about your environment:**
OSX 10.12.6

**Current behavior:**
Source HTML like the following:

```html
<picture>
  <source
    type="image/webp"
    srcset="./images/300_sofa_pug.jpg.webp 300w,
      ./images/600_sofa_pug.jpg.webp 600w" />
  <img
    srcset="./images/300_sofa_pug.jpg 300w,
      ./images/600_sofa_pug.jpg 600w"
    src="./images/600_sofa_pug.jpg"
    sizes="(max-width: 320px) 280px,
      (max-width: 640px) 580px,
      1000px"
    alt="puppy in a striped shirt" />
</picture>
```

Builds to:
```html
<picture>
  <source type=image/webp srcset="./images/300_sofa_pug.jpg.webp 300w, ./images/600_sofa_pug.jpg.webp 600w" />
  <img srcset="./images/300_sofa_pug.jpg 300w, ./images/600_sofa_pug.jpg 600w" src=/images/600_sofa_pug.b00758fdf2078ef0fc04c9f3941b8db5.jpg
    sizes="(max-width: 320px) 280px,
      (max-width: 640px) 580px,
      1000px" alt="puppy in a striped shirt" />
</picture>
```
and only the file listed in `src` is loaded by `html-loader` and processed (by other loaders).

**Expected/desired behavior:**
It should require the image files listed in `srcset` so the build file would look something like this:
```html
<picture>
  <source type=image/webp srcset="./images/300_sofa_pug.d00yyyfdf2078ef0fc04c9f3941b8db5.jpg.webp 300w, ./images/600_sofa_pug.c00xxxfdf2078ef0fc04c9f3941b8db5.jpg.webp 600w" />
  <img srcset="./images/300_sofa_pug.e00zzzfdf2078ef0fc04c9f3941b8db5jpg 300w, ./images/600_sofa_pug.f00aaafdf2078ef0fc04c9f3941b8db5.jpg 600w" src=/images/600_sofa_pug.b00758fdf2078ef0fc04c9f3941b8db5.jpg
    sizes="(max-width: 320px) 280px,
      (max-width: 640px) 580px,
      1000px" alt="puppy in a striped shirt" />
</picture>
```
And all files listed in `srcset` are loaded by `html-loader` for processing (by another loader). I just put in fake hashes for illustrative purposes.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
See above code sample - just put it in an HTML file.

* **What is the expected behavior?**
see above

* **What is the motivation / use case for changing the behavior?**
To load files used in valid HTML attributes.
 
* **Browser:** all 
 
* **Language:** HTML

**Comment by netdjw** [comment]
Same issue here.

webpack 4.27.1
html-loader 0.5.5

under Windows 10

**Comment by evilebottnawi** [comment]
Feel free to send a PR

**Comment by coursar** [comment]
@siakaramalegos you can npm install from PR that already has support for requested feature

**Comment by siakaramalegos** [comment]
Any update on this? It looks like a PR was opened, but hasn't been addressed yet.

**Comment by tim1016** [comment]
Same issue here. srcset images are not loaded

**Comment by coursar** [comment]
@tim1016 are you use PR version or master?

**Comment by yin-june** [comment]
> Same issue here.
> 
> webpack 4.27.1
> html-loader 0.5.5
> 
> under Windows 10
> 
> I'm using this webpack cofing:
> 
> ```
>       {
>         test: /\.html$/,
>         use: {
>           loader: 'html-loader',
>           options: {
>             interpolate: true,
>             attrs: ['img:src', ':srcset']
>           }
>         }
>       }
> ```

No help. Will throw an Error: Can`t resolve './images/300_sofa_pug.jpg.webp 300w, ./images/600_sofa_pug.jpg.webp 600w'
Because html-loader will not parse the srcset syntax.

**Comment by coursar** [comment]
> Same issue here. srcset images are not loaded
> @coursar,
> current version were install using npm i webpack
> (versions are: "webpack": "^4.39.2",
> "webpack-cli": "^3.3.6",
> "webpack-dev-server": "^3.8.0")
> Using on Linux.
> 
> Do I use the PR version like the following?
> npm install webpack/webpack.git#pull//head
> 
> Am I wrong somewhere.

Docs: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
Sample: `npm i -D git+https://github.com/webpack-contrib/html-loader#pull/192/head`

Use it with caution: it's unmaintained

**Comment by siakaramalegos** [comment]
I've been using `html-loader-srcset` instead https://www.npmjs.com/package/html-loader-srcset
