### ISSUE TITLE
Not resolved src-attributes from js files

### ISSUE THREAD

**Issue by mihalt** [webpack-contrib/html-loader#189]
**Webpack version:**
4.26.1

**HTML-Loader version:**
0.5.5

**Please tell us about your environment:**
Windows 10

**Current behavior:**
Paths in src-attribute's in created and inserted html-tags from javascript, don't resolved. Is it ok? 

Tried to add html-loader on js-files, but as I see it is not the best idea. Css-files don't downloaded.

**Comment by mihalt** [comment]
@evilebottnawi get it — https://github.com/mihalt/html-loader-bug

**Comment by evilebottnawi** [comment]
It is expected, you need use `const url = require('./image.png');` in JS files
