### ISSUE TITLE
Writing your own html?

### ISSUE THREAD

**Issue by tr1s** [webpack-contrib/html-loader#190]
Sorry if this is the wrong place to ask..

How do I write my own html and have it minify into /dist? I half figured it out.. I got it minified into /dist but If I write my own html then I have `<script src="./src/index.js">` so it's connected to all my js/styles etc, but I would want it exported as `<script src="./dist/index.js">` in the html on build so when I upload to my website servers or use webpack-dev-server it'll serve the right assets and be styled.

The problem is I want to write my own html (for basic static sites) and I can't seem to wrap my head around this concept. I'd like to enjoy what Webpack 4 offers but write my own html.

**Comment by evilebottnawi** [comment]
You can use HtmlWebpackPlugin (a lot of features) or use CopyWebpackPlugin and just copy `html` file to `dist` (easy and simple)
