### ISSUE TITLE
Overwrite `HtmlWebpackPlugin` `<%= %>` expression

### ISSUE THREAD

**Issue by zhaoyi0113** [webpack-contrib/html-loader#195]
**I'm submitting a bug report**

**Webpack version:** "^4.28.2"

**HTML-Loader version:** "^0.5.5",

**Please tell us about your environment:**
OSX 10.x 

I am using `HtmlWebpackPlugin` in webpack and below is its configuration:

    new HtmlWebpackPlugin({
            filename: 'index.html',
            template: 'index.html',
            inject: 'body',
            sdk: '/mylib.js'
          })

In my `html` I define the `script` tag as:

    <script src="<%= htmlWebpackPlugin.options.sdk %>"></script>

webpack will replace the `<%= htmlWebpackPlugin.options.sdk %>` with `/mylib.js`. However it doesn't work once I add the `html-loader` plugin as below:

    {
              test: /\.html$/,
              use: [
                {
                  loader: 'html-loader',
                  options: {
                    attrs: 'img:src'
                  }
                }
              ]
            }

The reason I use `html-loader` is to parse the `img src` tag on html file. But it conflicts with `HtmlWebpackPlugin` `<%= ... %>` expression. How can I make both of them work?

**Comment by mapacarta** [comment]
I am having the same problem and I couldn't find any solution yet.

**Comment by michaelvinci** [comment]
Here is the solution I eventually found to resolve `html-loader` issues while using `HTMLWebpackPlugin`:

1. Install `ejs-loader` and `extract-loader` 

2. Change `HTMLWebpackPlugin` config to:
```
new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'src/templates/index.ejs'
})
```

3. Set up this module rule:
```
{
        test: /\.ejs/,
        use: [
          'extract-loader',
          'html-loader',
          'ejs-loader'
        ]
      },
```
Now I can run my templates through `HTMLWebpackPlugin` and still use `html-loader` to parse `img` tags. Hopefully this helps!

Here is more info:
https://github.com/webpack-contrib/html-loader#export-into-html-files

**Comment by DimaGashko** [comment]
> Here is the solution I eventually found to resolve `html-loader` issues while using `HTMLWebpackPlugin`:
> 
> 1. Install `ejs-loader` and `extract-loader`
> . . . 
> ```
> {
>         test: /\.ejs$/,
>         use: [
>           'extract-loader',
>           'html-loader',
>           'ejs-loader'
>         ]
>       },
> ```
> 

Thanks, but this solutions doesn't work with aliases properly. 

```js
alias: {
     '@': path.resolve(__dirname, './'),
     'img': path.resolve(__dirname, './images'),
}
```

```html
<img src="~@/image/blog.jpg" alt="some image"> <!-- doesn't work -->
<img src="~/img/blog.jpg" alt="some image"> <!-- doesn't work -->

<img src="~@/../../image/blog.jpg" alt="some image"> <!-- works, I've no idea why -->
<img src="~/../../img/blog.jpg" alt="some image"> <!-- doesn't work -->
``

**Comment by DimaGashko** [comment]
Ok, I understood. Solution above works well. It's  extract-loader@3.* has error.

This works for me:

```json
"extract-loader": "^2.0.0"
```

```js
 use: [
        'ejs-loader',
        'extract-loader',
        'html-loader',
],
```

**Comment by evilebottnawi** [comment]
`HtmlWebpackPlugin` already has loader, i think you don't need `html-loader`

**Comment by DimaGashko** [comment]
I know that. Unfortunately HtmlWebpackPlugin doesn't 'load' images and other resources.
And I don't want use something like this `<%= require('. . .') %>`, I really want use just `<img src="./img.jpg"` or `<img src="~images/img.jpg">`.

If there's a solution for this by HtmlWebpackPlugin, plese text about it

**Comment by hg-pyun** [comment]
Good. I also works.

**Comment by study-loading** [comment]
https://github.com/webpack-contrib/html-loader#interpolation
use interpolate flag to enable interpolation syntax for ES6 template strings

**Comment by evilebottnawi** [comment]
html-loader handle only html, so you need ejs-loader for handle `<%= %>`, we will merge html support out of box in webpack@5 and simplify that and this problem will disappear, at the moment, unfortunately we can not do anything

**Comment by fwh1990** [comment]
> html-loader handle only html, so you need ejs-loader for handle `<%= %>`, we will merge html support out of box in webpack@5 and simplify that and this problem will disappear, at the moment, unfortunately we can not do anything

And webpack@5 is released now, what to do next step?
