### ISSUE TITLE
Switch to CircleCi 2.0

### ISSUE THREAD

**Issue by Gaspacchio** [webpack-contrib/html-loader#197]
**I'm submitting a bug report**

**Webpack version:**
^4.29.3

**HTML-Loader version:**
^0.5.5

**Please tell us about your environment:**
Linux (Debian 9)

**Current behavior:**
All the tests are done on CircleCi 1.0

**Expected/desired behavior:**
Tests should be done on CircleCi 2.0, as 1.0 is closing its support on March 15, 2019
> Starting March 15, 2019, all jobs referencing 1.0 in their configuration will cease to run.
> [Sunsetting CircleCI 1.0](https://circleci.com/sunset1-0/)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
Not appliccable

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Support the future of html-loader!
 
* **Browser:** all

**Comment by evilebottnawi** [comment]
We will migrate on azure soon
