### ISSUE TITLE
NPM Audit vulnerability "Code Injection" from sub-dependency js-yaml

### ISSUE THREAD

**Issue by hdpinto** [webpack-contrib/html-loader#199]
**I'm submitting a bug report**

**Webpack version:**
N/A

**HTML-Loader version:**
1.0.0-alpha.0

**Please tell us about your environment:**
N/A

**Current behavior:**
![image](https://user-images.githubusercontent.com/1548970/56246979-6004a980-6071-11e9-90c0-de6b7ee976e9.png)

**Expected/desired behavior:**
Updated dependencies to fix vulnerability

**Comment by MattIPv4** [comment]
Any updates on resolving this?

**Comment by evilebottnawi** [comment]
Please use master branch, next is not ready, thanks
