### ISSUE TITLE
url-loader not loading the image when using interpolation directly on the img src

### ISSUE THREAD

**Issue by ariel42** [webpack-contrib/html-loader#200]
**I'm submitting a bug report**

**Webpack version:** 4.32.2

**HTML-Loader version:** 0.5.5

**Please tell us about your environment:** Windows 10

**Current behavior:**
url-loader is not working if interpolation is used directly on the img src, the file is handled by file-loader instead.

I'm trying to embed with url-loader all the files from images/url folder, and load normally with file-loader all the other images.

Here is my loader configuration (sorry for the bad indentation):
`{`
  `test: /images[\\/]url[\\/].+$/i,`
  `use: [`
  `{`
    `loader: 'url-loader'`
  `            }`
`          ]`
`        },`
`        {`
`          test: /\.(png|jpe?g|gif|svg|webp)$/i,`
`          exclude: /images[\\/]url[\\/].+$/i,`
`          use: [`
`            {`
`              loader: 'file-loader',`
`              options: {`
`                name: 'images/[name].[hash:8].[ext]'`
`              }`
`            }`
`          ]`
`        },`
`        {`
`          test: /.html$/,`
`          use: [`
`            {`
`              loader: 'html-loader',`
`              options: {`
`                minimize: false,`
`                interpolate: true`
`              }`
`            }`
`          ]`
`        }`

Now in the html file, this doesn't work:
`<img class="yes-no" src="${1 === 1 ? images/url/yes.png : images/url/no.png}">` (the paths are wrapped with back-ticks)
I'm getting the correct image but not url embedded.

However this works (so currently I'm using it as a workaround):
`${1 === 1 ?`
    `<img class="yes-no" src="images/url/yes.png">` - line wrapped with back-ticks
   `:`
    `<img class="yes-no" src="images/url/no.png">` - line wrapped with back-ticks
  `}`

**Expected/desired behavior:**
Embed the correct image with url-loader, even when using the interpolation directly on the img src itself.

**Comment by schryer** [comment]
I can confirm this bug.

**Comment by evilebottnawi** [comment]
If you use `interpolation` you need import images directly, for example:
```
<img class="yes-no" src="${value === 1 ? require('./yes.png') : require('./no.png')}">
```

Also you need setup url-loader or file-loader
