### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by Legends** [webpack-contrib/html-loader#204]
**I'm submitting a bug report**

>  ERROR in ./src/pages/home/layout.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/pages/home/layout.html)
>     Module build failed (from ./node_modules/**html-loader**/index.js):
>     Error: **Line 14: Unexpected identifier**
>         at ErrorHandler.constructError (C:\Users\xxxxxx\node_modules\esprima\dist\esprima.js:3396:22)

**Line 14 is the where the** `catch` **statement is.**

Layout.html 
```
 <script>
        if ('serviceWorker' in navigator) {
            window.addEventListener('load', () => {
                navigator.serviceWorker.register('p-cache.js') // register the serviceWorker
                    .then(reg => console.log('Service Worker: Registered (Pages)'))
                    .catch(err => console.log(`Service Worker: Error: ${err}`));   // <-- Line 14
            });
        }
    </script>
```

Layout.html is configured as a template page in webpack.config:
 `new HtmlWebpackPlugin({ template :  './src/pages/home/layout.html',`

Everything works fine until I put this script into the head seaction.

**Webpack version:**
4.41.2

**HTML-Loader version:**
 "html-loader": "^0.5.5",

**Please tell us about your environment:**
Windows 10

**Current behavior:**
Error

**Expected/desired behavior:**
No Error

**Comment by Legends** [comment]
It looks like that it doesn't like the string interpolation part:

\`Service Worker: Error: ${err}\`

**Comment by evilebottnawi** [comment]
Can you create reproducible test repo? Maybe problem on `HtmlWebpackPlugin` side

**Comment by Legends** [comment]
Here is the [repo](https://github.com/Legends/UnxpectedIdentifier)

Just run: `yarn dev`

**Comment by evilebottnawi** [comment]
Thanks! In near future we will refactor html-loader code, so i think i will fix it

**Comment by evilebottnawi** [comment]
`html-minifier` uses `uglify-js` and that package do not support ES6 syntax
