### ISSUE TITLE
Cite prehtml-loader in documentation ?

### ISSUE THREAD

**Issue by denis-migdal** [webpack-contrib/html-loader#206]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?
- [X] Other

### Please Explain in Detail...

I just created a new loader that can be chained with html-loader, that enables to provide parameters for html-loader interpolation:
https://github.com/denis-migdal/prehtml-loader

This seems to be an asked feature, as shown by the following issues:
https://github.com/webpack-contrib/html-loader/issues/120
https://github.com/webpack-contrib/html-loader/issues/122
https://github.com/webpack-contrib/html-loader/issues/184

(sorry if I flooded a little the issues).

### Your Proposal for Changes

Could it be possible to cite my loader in your documentation ?

This is my first npm package, so if you have any suggestion on what I should to, feel free to create an issue in my git repository:
https://github.com/denis-migdal/prehtml-loader/issues

**Comment by evilebottnawi** [comment]
Yes, PR welcome

**Comment by denis-migdal** [comment]
I will try to submit a PR in few hours.

I am currently adding 2 extra-features to my loader:
* support of import (convert it into a require) for html-loader;
* support of templates (I am currently thinking how to achieve this).

**Comment by denis-migdal** [comment]
Done: https://github.com/webpack-contrib/html-loader/pull/211

Please note that my loader is very new (today), so I can't guarantee that there will be no issues.

**Comment by evilebottnawi** [comment]
Thanks for the issue, i think will be great to put thath into https://github.com/webpack-contrib/awesome-webpack repo, feel free to send a PR :+1: You can add examples to own README
