### ISSUE TITLE
minimize=true is stripping invalid css

### ISSUE THREAD

**Issue by Zauberfisch** [webpack-contrib/html-loader#213]
- Operating System: arch linux
- Node Version: 13.6.0
- NPM Version: 6.13.6
- webpack Version: 4.41.2
- html-loader Version: unknown

I understand that the minimizer is trying to optimise for size, but in the process it strips invalid css from a style tag. I believe that this is undesirable behaviour.  
In a normal case that might actually be the right thing to do, but some libraries/frameworks/loaders might depend on a not-valid-css string to be there to perform custom transformations or custom behaviour.

### Expected Output for `{attrs: false, minimize: true}`
`<div style="invalid css here">`

### Actual Output for `{attrs: false, minimize: true}`
`<div style="">`. 

### Expected Output for `{attrs: false, minimize: false}`
`<div style="invalid css here">`

### Actual Output for `{attrs: false, minimize: false}`
`<div style="invalid css here">`

### Code

```js
// webpack.config.js
{
				test: /\.customTemplateExtension$/,
				use: [
					{
						loader: 'file-loader',
						options: {
							name: '[name].otherCustomTemplateExtension',
							esModule: false,
							outputPath: '../../app/templates',
						},
					},
					'extract-loader',
					{
						loader: 'html-loader',
						options: {
							attrs: false,
							minimize: true,
						}
					}
				],
			}
```

```js
// foobar.customTemplateExtension
<div style="invalid value here"></div>
```

**Comment by evilebottnawi** [comment]
Please open issue in `html-minifier` repo

**Comment by Zauberfisch** [comment]
I'm not sure it's exactly a bug in html-minifier. There is an option `minifyCSS` on html-minifier.

**Comment by evilebottnawi** [comment]
Workaround - set `minifyCSS` to `false`. The issue https://github.com/DanielRuf/html-minifier-terser/issues/27

**Comment by DanielRuf** [comment]
**Solution**

There is a way to prevent that:
https://github.com/jakubpawlowicz/clean-css#how-to-keep-a-css-fragment-intact

This is already supported through `clean-css`.
Use the `/* clean-css ignore:start */` and `/* clean-css ignore:end */` comments.

`<div style="/* clean-css ignore:start */invalid css here/* clean-css ignore:end */">test</div>`

<img width="832" alt="Bildschirmfoto 2020-01-22 um 00 50 36" src="https://user-images.githubusercontent.com/827205/72853314-5586d880-3cb1-11ea-8bd1-95b85d11fbf8.png">

**Comment by DanielRuf** [comment]
So actually not a bug ;-)

**Comment by evilebottnawi** [comment]
@DanielRuf Unfortunately this is not the best behavior, in theory in future developers can use new CSS syntax and due clean-css do not support that it is break code, so it is bug, will be great to keep `style` tags as is if something wrong with syntax

**Comment by DanielRuf** [comment]
> @DanielRuf Unfortunately this is not the best behavior, in theory in future developers can use new CSS syntax and due clean-css do not support that it is break code, so it is bug, will be great to keep `style` tags as is if something wrong with syntax

I don't agree with this.

Not possible without breaking the current implementation. Also wrapping everything in a style attribute into these comments prevents minifying css at all in the style attributes which makes not much sense. This should be controllable and it is controllable with these comments. It is just not documented.

**Comment by evilebottnawi** [comment]
@DanielRuf 

> I don't agree with this.

Really? Would you expect from a babel or typescript empty string on invalid syntax or you wait exception and keep code in files as is?

**Comment by DanielRuf** [comment]
Afaik html-minifier and clean-css accept and generate only valid code.

**Comment by DanielRuf** [comment]
> As i written in the original issue, we should got an exception when a syntax is broken, so when we got an exception we return original string instead return empty string.

See my reply in the linked issue. It should normally. This is an upstream issue in clean-css as far as I can see.

**Comment by evilebottnawi** [comment]
> Afaik html-minifier and clean-css accept and generate only valid code.

The problem is that clean-css does not recognize the new syntax what support new browsers and return broken code, so it is bug.

**Comment by DanielRuf** [comment]
> does not recognize the new syntax what support new browsers and return broken code, so it is bug.

The issue was about something else:

> <div style="invalid css here">

**Comment by alexander-akait** [comment]
Sorry we can't fix it here, please report about it in `html-minifier-terser` or disable it using https://github.com/webpack-contrib/html-loader?tab=readme-ov-file#minimize
