### ISSUE TITLE
[v0.5.5] minimize=false not being respected

### ISSUE THREAD

**Issue by chiplay** [webpack-contrib/html-loader#23]
I'm setting the html-loader query to `minimize=false` in my webpack config, but when bundled for production and uglyfied, html is still getting compressed (eg. whitespace removed, input type=text remove, etc).  Any ideas how to work around this? I'd love to use uglify as part of webpack and not a seperate build step.

**Comment by gajus** [comment]
This will be fixed as soon as this PR is accepted, https://github.com/webpack/html-loader/pull/24.

**Comment by chiplay** [comment]
thanks @gajus :+1:

**Comment by jackyon** [comment]
looks like this issue still existed.

**Comment by hemanth** [comment]
#24 was closed without reasons, waiting on this.
