### ISSUE TITLE
Publish new version of html-loader

### ISSUE THREAD

**Issue by maksimr** [webpack-contrib/html-loader#239]
The latest published version of html-loader(`0.5.5` 2 years old) has only `img:src` as default for attributes. But the documentation says and in the code on github default attributes are:

```
            ':srcset',
            'img:src',
            'audio:src',
            'video:src',
            'track:src',
            'embed:src',
            'source:src',
            'input:src',
            'object:data',
```
https://github.com/webpack-contrib/html-loader/blob/master/src/plugins/attribute-plugin.js#L432-L442

**Comment by evilebottnawi** [comment]
The next version is still in progress, ETA is next week
