### ISSUE TITLE
options.attributes is no valid key to use in 0.5.5

### ISSUE THREAD

**Issue by flipcc** [webpack-contrib/html-loader#245]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Documentation concerning [*attributes*](https://webpack.js.org/loaders/html-loader/#attributes) states that `options.attributes` is a valid key, but in `"html-loader": "^0.5.5"` it is not. Following change finally made my project work:

```diff
...
{
  loader: 'html-loader',
    options: {
-      attributes: ['link:href'],
+      attrs: ['link:href'],
        ...
    }
}
...
```

### Your Proposal for Changes

Adapt the documentation for `"html-loader": "^0.5.5"` to state that *attr* instead of *attributes* needs to be used. I looked into [commit *a80fc7e7693f31b6975046befdec95e1a8bb4f60*](https://github.com/webpack-contrib/html-loader/commit/a80fc7e7693f31b6975046befdec95e1a8bb4f60#diff-2383962d8d2b221a0b501d8347a62591) and saw that in the future it is going to be *attributes*, but at the moment this is just misleading people.

**Comment by evilebottnawi** [comment]
We have next branch in master and will do release in near future, old docs you can find here https://github.com/webpack-contrib/html-loader/tree/v0.5.5

**Comment by flipcc** [comment]
[www.npmjs.com](https://www.npmjs.com/package/html-loader) still states the correct syntax.

**Comment by evilebottnawi** [comment]
Yes, because npm contains docs for the `0.5.5` tag

**Comment by flipcc** [comment]
All good, we commented at the same time.
