### ISSUE TITLE
Allow "any" tag in `attributes.list[0].tag`

### ISSUE THREAD

**Issue by andreyvolokitin** [webpack-contrib/html-loader#267]
- Operating System: any
- Node Version: any
- NPM Version: any
- webpack Version: any
- html-loader Version: any

### Feature Proposal
Would it make sense to support any tag inside `attributes.list[0].tag`? I.e.:
```js
{
  tag: '*',
  attribute: 'data-lazy',
  type: 'src',
 },
```
### Feature Use Case
In this case we could skip writing many objects for each tag with same custom attribute (i.e. `data-lazy`)

---
I can help with PR

**Comment by evilebottnawi** [comment]
Yep, let's do it, if the `tag` property do not setup-ed handle all tags instead `tag: '*'`
