### ISSUE TITLE
when options.minimize: Object, it doesn't inherit default options

### ISSUE THREAD

**Issue by gulping** [webpack-contrib/html-loader#268]
- Operating System: macOS 10.15.4
- Node Version: v13.7.0
- NPM Version: 6.13.6
- webpack Version: 4.42.1
- html-loader Version: 1.0.0

### Actual Behavior

when options.minimize: Object, it doesn't inherit default options.

### Expected Behavior

inherit default options.

### Code

```js
// webpack.config.js
        ......
        loader: 'html-loader',
        options: {
          minimize: true,
        },
        ......
```

→ the result has NO line breaks. (minified)

```js
// webpack.config.js
        ......
        loader: 'html-loader',
        options: {
          minimize: {},
        },
        ......
```

→ the result has line breaks.

```js
// webpack.config.js
        ......
        loader: 'html-loader',
        options: {
          minimize: {
            collapseWhitespace: true,
          },
        },
        ......
```

→ the result has NO line breaks.

**Comment by evilebottnawi** [comment]
It is expected, you should list all possible values when use object notation

**Comment by evilebottnawi** [comment]
You can get them from https://github.com/webpack-contrib/html-loader/blob/master/src/plugins/minimizer-plugin.js#L7

**Comment by gulping** [comment]
thanks for help!

the old document misled me, so please update it
https://github.com/webpack-contrib/html-loader#object-1
