### ISSUE TITLE
Import error with ES6 js script embedded in html body

### ISSUE THREAD

**Issue by benjaminpreiss** [webpack-contrib/html-loader#270]
- Operating System: Windows 10 Pro
- Node Version: 13.12.0
- NPM Version: 6.14.4
- webpack Version: 4.42.1
- html-loader Version: 1.0.0

### Expected Behavior
html-loader should process `index.html` and pass the embedded ES6 js script to babel loader.
### Actual Behavior
Running `npx webpack` resp. `npm run webpack` returns this error:

```
ERROR in ./src/html/index.html
Module build failed (from ./node_modules/extract-loader/lib/extractLoader.js):
C:\ ... \website\src\index.js:1
(function (exports, require, module, __filename, __dirname) { import { gsap } from 'gsap';
                                                              ^^^^^^

SyntaxError: Cannot use import statement outside a module
...
```
### Code

[**webpack.config.js** and  **package.json**](https://gist.github.com/benjaminpreiss/3219e4d44a6ae36b67c0550938b113ca)

**index.html**:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    ...
</head>
<body id="#body">
    <script type="module" src="../index.js"></script>
</body>
</html>
```

**index.js**:
```
import { gsap } from 'gsap';
import fullpage from 'fullpage.js';
import $ from 'jquery';

var ...
```

### How Do We Reproduce?

File structure:

```
 - src/
         - html/
                - index.html
         - index.js

 - dist/
 - webpack.config.js
 - package.json
```

Then run `npm run webpack`

**Comment by evilebottnawi** [comment]
Please create full reproducible test repo

**Comment by evilebottnawi** [comment]
Looks `extract-loader` is broken

**Comment by evilebottnawi** [comment]
Yes, broken `extract-loader`, please open an issue in `extract-loader` repo, we can't fix it on our side, sorry

**Comment by nick-woodward** [comment]
For those who find this issue, here's a link to the related issue on `extract-loader`.

https://github.com/peerigon/extract-loader/issues/79
