### ISSUE TITLE
Optional default unescaped characters

### ISSUE THREAD

**Issue by bosens-China** [webpack-contrib/html-loader#271]
- Operating System:
win10
- Node Version:
v13.9.0
- NPM Version:
6.13.7
- webpack Version:
4.42.1
- html-loader Version:
1.0.0

### Feature Proposal
Accepts a function or string. If it is a function, the address to be processed is passed to the function itself, with the return value boolean as the result. If true, it needs to be processed by some other loader. If false, it is not processed.

### Feature Use Case
``` js
  options: {
    // ...other options
    noEscape: '/', // OK，Will not be passed to the next loader
    // or
    noEscape: (url) => {
      return !/^\//.test(url);
    },
  },
```

**Comment by evilebottnawi** [comment]
I don't understand what do you want, please clarify what do you want achieve with example(s)

**Comment by bosens-China** [comment]
What starts with `'/'` will not be escaped by `html-loader`. I want you to add a custom behavior for it

**Comment by evilebottnawi** [comment]
What do you mean `escaped`?

**Comment by xsfour** [comment]
[options.attributes.urlFilter](https://github.com/webpack-contrib/html-loader#urlfilter) may help.

**Comment by evilebottnawi** [comment]
Yes, I think you search the option above
