### ISSUE TITLE
Minimize Schema structured data (json-ld)

### ISSUE THREAD

**Issue by mauriciabad** [webpack-contrib/html-loader#281]
- Operating System: Windows
- Node Version: v13.11.0
- NPM Version: 6.13.7
- webpack Version: ^4.41.5
- html-loader Version: ^0.5.5

### Feature Proposal
When minimize is enabled minify the content of the script tags with "application/ld+json" type like a js file:
```html
<script type="application/ld+json">
  minify this
</script>
```

### Feature Use Case
Anyone using microdata may benefit of this. Specially developers working on SEO.

This is the code I get now in production, as you can see everything is in the same line except some elements in the header, one being the `json-ld` script tag.
![2020-04-14 19_16_01-package json - hackupc-landing - Visual Studio Code](https://user-images.githubusercontent.com/12821361/79254292-cd196d80-7e84-11ea-87f2-76b4907a0b61.png)

**Comment by evilebottnawi** [comment]
I think you need open a new issue here https://github.com/DanielRuf/html-minifier-terser :smile: We use that package for minify html

**Comment by evilebottnawi** [comment]
Look here - https://github.com/DanielRuf/html-minifier-terser/issues/34, you can be champion :+1:

**Comment by mauriciabad** [comment]
Okay, I'll follow that issue. Thanks 😊
