### ISSUE TITLE
Runtime injection example

### ISSUE THREAD

**Issue by bolein** [webpack-contrib/html-loader#283]
Hi, people of url-loader.

## Documentation
- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Details

I am lacking an example of injecting the resulting html at runtime. When I try doing it like the following:
```JS
import html from './index.html';
document.body.innerHTML += html;
```
I end up having scripts and styles like this in my resulting page: 
```HTML
<script src="[object" object]=""></script>
```
Since I have all the scripts bundled in the `bundle.js`, I would probably like to remove them from the original page.

Also, I am probably injecting it wrong, because by the time the html is appended, some DOM events have fired already and the page misses out!

Here are my rules:
```JS
{
  test: /\.css$/,
  use: [
    'style-loader',
    'css-loader',
  ],
},
{
  test: /\.(svg|gif|woff|woff2|eot|ttf|otf|png|jpe?g)$/i,
  use: [
    {
      loader: 'file-loader',
      options: {
        esModule: false
      },
    },
  ],
},
{
  test: /\.js$/i,
  exclude: /(node_modules|bower_components)/,
  use: {
    loader: 'babel-loader',
    options: {
      presets: ['@babel/preset-env']
    }
  }
},
{
  test: /\.html$/i,
  loader: 'html-loader',
},
```

I am also using `HtmlWebpackPlugin`

### Your Proposal for Changes
Let's add an example of this extremely common use case to the docs!

**Comment by evilebottnawi** [comment]
Do not disable `esModule`, keep it true or you can use `html.__esModules ? html.default : html`

**Comment by bolein** [comment]
Hi @evilebottnawi ! Thanks, but that didn't help! Also, would you be so kind to give me an idea on how to not miss the `onload` events in the injected html?

**Comment by evilebottnawi** [comment]
We don't have `onload` event, please create reproducible test repo

**Comment by evilebottnawi** [comment]
Oh, looks you need `file-loader`, you can do it:

Rename file in `src` to `scripts.file.js`

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.html$/i,
        loader: 'html-loader'
      },
      // Use babel for file in `src` and return public path to script
      {
        test: /\.file.js$/i,
        use:['file-loader', 'babel-loader']
      },
    ],
  },
};
```
```

**Comment by bolein** [comment]
@evilebottnawi thanks again for your help. Your option will inline the scripts, but what if I want them to get bundled in a single bundle.js?

**Comment by evilebottnawi** [comment]
> I want them to get bundled in a single bundle.js?

What do you mean?

**Comment by bolein** [comment]
@evilebottnawi nevermind, I don't think what I said makes sense.

Nevertheless, going back to the title of this issue: can you give me an example of how to correctly inject the resulting html into a page?

For example, it seems like in my generated html there are scripts that are seemingly dependent on the window.onload event, which never gets delivered because my injection method happens too late.

**Comment by evilebottnawi** [comment]
@bolein Sorry, I can't understand what do you want to achieve, you can do import using `import file from './file.html'`, you can do async improve - `import('./index.html').then().catch()`
