### ISSUE TITLE
Process script and link tags does not work

### ISSUE THREAD

**Issue by mkausl** [webpack-contrib/html-loader#284]
- Operating System: macos catalina 
- Node Version: v12.13.1
- NPM Version: 6.13.6
- webpack Version: 5.0.0-beta.15 (also tried with latest 4.x)
- html-loader Version: 1.1.0

### Expected Behavior

I tried the example "Process script and link tags" from the README.

```
module.exports = {
    entry: {
        index: './src/index.html'
    },
    module: {
        rules: [
            {
                test: /\.html$/i,
                use: ['file-loader?name=[name].[ext]', 'extract-loader', 'html-loader'],
            },
            {
                test: /\.js$/i,
                exclude: /\.file.js$/i,
                loader: 'babel-loader',
            },
            {
                test: /\.file.js$/i,
                loader: 'file-loader',
            }
        ],
    }
};
```

index.html contains `<script src="./app.file.js"></script>`

### Actual Behavior

index.html output contains `    <script src=[object Object]></script>`

### Code

see above

### How Do We Reproduce?

Setup the example "Process script and link tags" from the README.

**Comment by evilebottnawi** [comment]
Please create full reproducible test repo, I can't reproduce, we have tests for this

**Comment by mkausl** [comment]
thanks for the fast reply. 
i zipped my project. just unzip and run `npx webpack`
[Archive.zip](https://github.com/webpack-contrib/html-loader/files/4558038/Archive.zip)

**Comment by evilebottnawi** [comment]
It is not supported right now, we have roadmap for this for webpack@5 https://github.com/webpack/webpack/projects/5#card-29122473

**Comment by dipeshba** [comment]
@evilebottnawi if i install webpack 5 beta will this work?

**Comment by evilebottnawi** [comment]
Not, sure, need test

**Comment by evilebottnawi** [comment]
Let's close in favor webpack@5, we can't fix it on our side

**Comment by x35a** [comment]
Hi all. I've face the same problem. 
so is there an option to insert a `<script src=''>` tag with correct src path?
@dipeshba @evilebottnawi
