### ISSUE TITLE
Regression in 1.0 when used in conjuntion with ejs-loader

### ISSUE THREAD

**Issue by aletorrado** [webpack-contrib/html-loader#285]
Hi, I'm using html-loader in conjuntion with ejs-loader as input to html-webpack-plugin, like this:

```
	module: {
		rules: [
			{
				test: /\.html$/,
				use: [
					'extract-loader',
					'html-loader',
					'ejs-loader',
				],
			},
...
		new HtmlWebpackPlugin({
			template: './index.html',
			inject: 'head',
			chunks: ['main'],
		}),
```

Since html-loader 1.0, when my html file has a resource such as an image being referenced multiple times, I'm noticing a strange behavior: the second time a resource is used, it's omitted and a reference to the next resource in the file is printed in it's place.
I'll try to illustrate this matter better. If my file is like this:
```
<img src="a.png" />
<img src="b.png" />
<img src="b.png" />
<img src="c.png" />
```
I'll get:
```
<img src="a.png" />
<img src="b.png" />
<img src="c.png" />
<img src="undefined" />
```
This isn't happening with v0.5.5 (latest v0).
Thanks!

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by aletorrado** [comment]
> Please create reproducible test repo

Ok! There it is: https://github.com/aletorrado/html-loader-regression

**Comment by evilebottnawi** [comment]
Bug in `extract-loader`, here https://github.com/peerigon/extract-loader/blob/master/src/extractLoader.js#L172, placeholders may be duplicated

For example:
```html
<img src="a.png" />
Text
<img src="a.png" />
```

We generate code:
```js
import src from ./a.png';'

export default '<img src="' + src + '" /><img src="' + src + '" />'
```

It is reduce runtime overhead. No need duplicate `import` on same source.

Please open a new issue in `extract-loader` repo, if you will have problems with fixing bug just ping me.
