### ISSUE TITLE
html placeholder get removed sometimes

### ISSUE THREAD

**Issue by Kobico-sap** [webpack-contrib/html-loader#287]
- Operating System: Windows
- Node Version: 13.5
- NPM Version: 6.13.1
- webpack Version: 4.43.0
- html-loader Version: 1.1.0

I have this html file:

&lt;div id=&quot;screen-dialog-page-overlay&quot; style=&quot;display:${overlayDisplay}&quot;&gt;&lt;/div&gt;
&lt;div class=&quot;screen-dialog-inner&quot;&gt;
    &lt;div class=&quot;screen-dialog-top&quot;&gt;
        &lt;div class=&quot;screen-dialog-caption&quot; id=&quot;screen-dialog-caption-${modalID}&quot;&gt;$title&lt;/div&gt;
        &lt;div class=&quot;screen-dialog-close&quot;&gt;&lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;

**_version 0.5.5 output:_**

'&lt;div id=&quot;screen-dialog-page-overlay&quot; style=&quot;display:${overlayDisplay}&quot;&gt;&lt;/div&gt;\r\n&lt;div class=&quot;screen-dialog-inner&quot;&gt;\r\n    &lt;div class=&quot;screen-dialog-top&quot;&gt;\r\n        &lt;div class=&quot;screen-dialog-caption&quot; id=&quot;screen-dialog-caption-${modalID}&quot;&gt;$title&lt;/div&gt;\r\n        &lt;div class=&quot;screen-dialog-close&quot;&gt;&lt;/div&gt;\r\n    &lt;/div&gt;\r\n&lt;/div&gt;'

**_version 1.1.0 output:_**

&quot;&lt;div id=screen-dialog-page-overlay style=display:{};&gt;&lt;/div&gt; &lt;div class=screen-dialog-inner&gt; &lt;div class=screen-dialog-top&gt; &lt;div class=screen-dialog-caption id=screen-dialog-caption-${modalID}&gt;$title&lt;/div&gt; &lt;div class=screen-dialog-close&gt;&lt;/div&gt; &lt;/div&gt; &lt;/div&gt;&quot;

### Expected Behavior
to output: style=display:${overlayDisplay}

### Actual Behavior
output is: style=display:{};

**Comment by evilebottnawi** [comment]
Because it is invalid html, so minimizer can't parse and minimize it in the right way, please use https://github.com/webpack-contrib/html-loader#preprocessor if you need templates
