### ISSUE TITLE
empty src throw an error

### ISSUE THREAD

**Issue by EnjoyChan** [webpack-contrib/html-loader#288]
- Operating System: mac
- Node Version: 10
- NPM Version: 6
- webpack Version: 4
- html-loader Version: 1.1.0

### Expected Behavior
with a warm tip that there has empt src, allow empty image src, with output src="" 

### Actual Behavior
throw an error, and stop the whole compilation

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
.use("html-loader")
    .loader("html-loader")
    .options({
      minimize: true,
    })
```

```js
// additional code, HEY YO remove this block if you don't need it
// I think the problem code pos
function parseSrc(input) {
  if (!input) {
    throw new Error('Must be non-empty');
  }

```

### How Do We Reproduce?

<img width="1296" alt="Xnip2020-05-27_12-32-23" src="https://user-images.githubusercontent.com/6998403/82978023-247b3380-a016-11ea-8f4c-bc8f574e7471.png">

**Comment by evilebottnawi** [comment]
Because it is HTML spec violation, `src` can't be empty.

https://html.spec.whatwg.org/multipage/embedded-content.html

> The src attribute gives the URL of the media resource. The value must be a valid non-empty URL potentially surrounded by spaces. This attribute must be present.

https://html.spec.whatwg.org/multipage/urls-and-fetching.html#valid-non-empty-url-potentially-surrounded-by-spaces
