### ISSUE TITLE
html-loader 6.0.1 breaks build

### ISSUE THREAD

**Issue by gugurete** [webpack-contrib/html-loader#289]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- html-loader Version:

### Actual Behavior

Html Webpack Plugin:
  Error: webpack-internal:///./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js:93
    var style = document.createElement('style');
                ^
  ReferenceError: document is not defined
  
  - injectStylesIntoStyleTag.js:93 insertStyleElement
    [.]/[style-loader]/dist/runtime/injectStylesIntoStyleTag.js:93:15
  
  - injectStylesIntoStyleTag.js:208 addStyle
    [.]/[style-loader]/dist/runtime/injectStylesIntoStyleTag.js:208:13
  
  - injectStylesIntoStyleTag.js:81 modulesToDom
    [.]/[style-loader]/dist/runtime/injectStylesIntoStyleTag.js:81:18
  
  - injectStylesIntoStyleTag.js:239 module.exports
    [.]/[style-loader]/dist/runtime/injectStylesIntoStyleTag.js:239:25
  
  - style.css:15 eval
    webpack-internal:///./src/assets/fonts/style.css:15:14
  
  - index.html:155 Object../src/assets/fonts/style.css
    /Users/robert/zenyem/bom/water-balance/water-balance-ui/src/index.html:155:1
  
  - index.html:21 __webpack_require__
    /Users/robert/zenyem/bom/water-balance/water-balance-ui/src/index.html:21:30
  
  - index.html:3 eval
    [.]/[html-webpack-plugin]/lib/loader.js!./src/index.html:3:34
  
  - index.html:132 Object../node_modules/html-webpack-plugin/lib/loader.js!./src/index.html
    /Users/robert/zenyem/bom/water-balance/water-balance-ui/src/index.html:132:1
  
  - index.html:21 __webpack_require__
    /Users/robert/zenyem/bom/water-balance/water-balance-ui/src/index.html:21:30

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by evilebottnawi** [comment]
You can't use `style-loader` in env where document is undefined
