### ISSUE TITLE
Uncaught Error: Template parse errors

### ISSUE THREAD

**Issue by Zadvornyi** [webpack-contrib/html-loader#292]
Hi everyone,
I have  Angular app version 9, which is compiled  by webpack.
I upgraded my html-loader from ^0.5.5 to ^1.0.0. After that, I got error.

<img width="1186" alt="Screenshot 2020-06-11 at 18 01 15" src="https://user-images.githubusercontent.com/10829855/84416957-9a3dec80-ac1d-11ea-8d23-06f9a1297e39.png">

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/html-loader/issues/269
