### ISSUE TITLE
source-plugin.js中decodeURIComponent解码特殊字符报错

### ISSUE THREAD

**Issue by yangdan8** [webpack-contrib/html-loader#294]
最新代码:
/dist/plugins/source-plugin.js:586行
const importKey = (0, _loaderUtils.urlToRequest)(decodeURIComponent(source.value), root);

报错:
URIError: URI malformed

 - decodeURIComponent

  - source-plugin.js:586 process
    [html-loader]/dist/plugins/source-plugin.js:586:5    4

  - utils.js:26 Object.process
    [html-loader]/dist/utils.js:26:19

  - URIError: URI malformed

  - compiler.js:80
    [html-webpack-plugin]/lib/compiler.js:80:16

  - Compiler.js:343
    [webpack]/lib/Compiler.js:343:11

  - Compiler.js:681
    [webpack]/lib/Compiler.js:681:15

调试得到:
source.value的值为./<%- htmlWebpackPlugin.options.assetsFileName %>.umd.js

decodeURIComponent解码特殊字符报错

**Comment by evilebottnawi** [comment]
Please use English, respect other developers
