### ISSUE TITLE
According to the demo file, an error occurred when extracting the js file

### ISSUE THREAD

**Issue by bosens-China** [webpack-contrib/html-loader#298]
- Operating System:win10
- Node Version:v14.2.0
- NPM Version:6.14.4
- webpack Version:^4.44.0
- html-loader Version:1.1.0

### Expected Behavior

The separate js file is pulled out
### Actual Behavior
ReferenceError: document is not defined

### Code

```js
// webpack.config.js
const path = require("path");

module.exports = {
  entry: "./src/index.html",
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "[name].js",
  },
  mode: "production",
  module: {
    rules: [
      {
        test: /\.html$/i,
        use: ["file-loader?name=[name].[ext]", "extract-loader", "html-loader"],
      },
      {
        test: /\.js$/i,
        exclude: /\.file.js$/i,
        loader: "babel-loader",
      },
      {
        test: /\.file.js$/i,
        loader: "file-loader",
      },
      {
        test: /\.css$/i,
        exclude: /\.file.css$/i,
        loader: "css-loader",
      },
      {
        test: /\.file.css$/i,
        loader: "file-loader",
      },
    ],
  },
};
```

Other files ...
Consistent with readme

### How Do We Reproduce?
https://github.com/bosens-China/html-error

**Comment by evilebottnawi** [comment]
HTML endpoints is not supported webpack yet, it was implemented for webpack@5, anyway with `extract-loader` it should work, but `extract-loader` can not handle `document`, please open a new issue in `extract-loader`, hope we will fix it in near future
