### ISSUE TITLE
Please add this to your index.js file "link:href, use:href" to make our lives easier.

### ISSUE THREAD

**Issue by abdulmomin123** [webpack-contrib/html-loader#307]
We need the link:href & use:href attribute support!

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/html-loader/blob/master/src/utils.js#L532 and https://github.com/webpack-contrib/html-loader/blob/master/src/utils.js#L527, release will be soon

**Comment by abdulmomin123** [comment]
thank you bro.

**Comment by abdulmomin123** [comment]
If you want i can do a pull request. I have it already working & and i'm using it.

**Comment by evilebottnawi** [comment]
@abdulmomin123 do pull request where?
