### ISSUE TITLE
How to get html-loader working with responsive-loader? 

### ISSUE THREAD

**Issue by 22mahmoud** [webpack-contrib/html-loader#309]
Is it possible to make html-loader automatically fill all img attributes while using responsive-loader ?

Expected 

```html
	<img src="*.jpg" srcSet="<all srcSet from the plugin>" width="<image.width>" height="<image.height>" />
```
Result

```html
	<img src="<only first src*.jpg>" />
```

you can check [my config](https://github.com/22mahmoud/mahmoudashraf.dev/blob/master/config/webpack/loaders.ts)

**Comment by evilebottnawi** [comment]
No, `responsive-loader` should provide loader for this logic, we can't solve it on our side
