### ISSUE TITLE
Templating - setting the data

### ISSUE THREAD

**Issue by buc-htl3r** [webpack-contrib/html-loader#318]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x ] Not Sure?

### Please Explain in Detail...

I'm not sure if this is missing in the documention or if it is a feature request. On other channels like stackoverflow I didn't receive any positive answers to my question. 

The [documentation](https://webpack.js.org/loaders/html-loader/#templating) explains how to use a template system with html-loader. But how can I set the data depending on the final-html page I would like to render?
Example: The following HtmlWebpackPlugin configuration triggers the html-loader. I would like to use the same template for different html pages but set the data for the template depending on the html page.

``` 
new HtmlWebpackPlugin({
      title: 'My App',
      filename: 'admin.html',
      template: 'src/page_template.hbs',
    }),
```

Please excuse if this is a complete nonsense. I'm fairly new to webpack. Thanks a lot!

### Your Proposal for Changes

Explain how to set data in the preprocessor depending on the final page which should be rendered.

**Comment by evilebottnawi** [comment]
We don't support templates, you need to use loader in this case or preprocessor option https://github.com/webpack-contrib/html-loader#templating

**Comment by buc-htl3r** [comment]
The preprocessor option is exactly the feature I'm refering to!

**Comment by evilebottnawi** [comment]
@buc-htl3r what do you want to document?

**Comment by buc-htl3r** [comment]
As I wrote initially I‘m not sure if the documentation is missing or the feature. I process a handlebar template as described in the link you mentioned. But as it is the purpose of a template, I would like to use the same template (o.e. .hbs file) to generate multiple html pages. For each generated page the provided data changes. How can I achieve this using the preprocessor? How can I set the data depending on the output file? Thanks!

**Comment by evilebottnawi** [comment]
@buc-htl3r Can you provide configuration or simple example how you try to achieve this?

**Comment by buc-htl3r** [comment]
Sure! In the example I would like to generate the pages "productA.html" and "productB.html" using the same template "src/product_template.hbs". My question is how I can set different data for the two pages in the preprocessor.

```
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      title: 'Product A',
      filename: 'productA.html',
      template: 'src/product_template.hbs',
    }),
    new HtmlWebpackPlugin({
      title: 'Product B',
      filename: 'productB.html',
      template: 'src/product_template.hbs',
    }),
    
],
module: {
  rules: [
    {
      test: /\.(jpe?g|png|gif|svg|ico)$/i,
      use: [{
          loader: 'file-loader',
          options: {
              name: '[contenthash].[ext]',
              outputPath: 'images/'
          }
      }]
    },
    {
      test: /\.hbs$/i,  
      loader: 'html-loader',
      options: {
        preprocessor: (content, loaderContext) => {
          let result;
          try {
            result = Handlebars.compile(content)({
              name: 'super product',
              price: '325.6',
            });
          } catch (error) {
            loaderContext.emitError(error);

            return content;
          }

          return result;
        },
      },
    },
  ],
}
};
```

**Comment by evilebottnawi** [comment]
@buc-htl3r You can use `json` files for this

**Comment by buc-htl3r** [comment]
@evilebottnawi How should it work with json files? Suppose I have a json as below. How can the preprocessor know which entry of the array it should take?

```
[
   {
      "name":"super product A",
      "price":325.6
   },
   {
      "name":"super product B",
      "price":42.9
   }
]
```
Thanks for your support!

**Comment by evilebottnawi** [comment]
```json
{
  "path/to/file": {
    "options": {
     "bar": "foo"
    }
  },
    "path/to/file": {
    "options": { 
      "foo": "bar"
    }
  }
}
```

**Comment by buc-htl3r** [comment]
@evilebottnawi I try to follow your thoughts but I don't get them. In the preprocessor I use the [handlebars](https://handlebarsjs.com/api-reference/runtime-options.html) library and I pass the data to the current compilation. How can I determine within the preprocessor if it is currently handling "path/to/fileA" or "path/to/fileB"? How does your json structure help? The example below won't work as it doesn't have a correct data structure for the template. Thanks!

```
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      title: 'Product A',
      filename: 'productA.html',
      template: 'src/product_template.hbs',
    }),
    new HtmlWebpackPlugin({
      title: 'Product B',
      filename: 'productB.html',
      template: 'src/product_template.hbs',
    }),
    
],
module: {
  rules: [
    {
      test: /\.(jpe?g|png|gif|svg|ico)$/i,
      use: [{
          loader: 'file-loader',
          options: {
              name: '[contenthash].[ext]',
              outputPath: 'images/'
          }
      }]
    },
    {
      test: /\.hbs$/i,  
      loader: 'html-loader',
      options: {
        preprocessor: (content, loaderContext) => {
          let result;
          try {
            result = Handlebars.compile(content)({
  "productA.html": {
    "options": {
        "name":"super product A",
        "price":325.6
    }
  },
  "productB.html": {
    "options": { 
        "name":"super product B",
        "price":42.9
    }
  }
});
          } catch (error) {
            loaderContext.emitError(error);

            return content;
          }

          return result;
        },
      },
    },
  ],
}
};
```

**Comment by evilebottnawi** [comment]
You need to load options manually, not pass them all:
```
const options = require('./path/to/options.json');

// ...
preprocessor: (content, loaderContext) => {
  const relativePath = path.relative(loaderContext.rootContext, loaderContext.resourcePath);
  const optionsForFile = options[relativePath];

  Handlebars.compile(content, optionsForFile);
});
```

**Comment by buc-htl3r** [comment]
If I look at loaderContext.resourcePath it contains the path to the template and not to the final file. Anyways, it doesn't seem possible what I want to achive as the loader seems to be called only once for each template. 

But then I don't understand the documented feature. What sense does it make to use a template with placeholders if I cannot use the template with different values for the placeholders?

**Comment by idudinov** [comment]
hi there! let me chime in with a question which I believe is very related and can help to resolve the original issue.

Is it possible in `preprocessor` to get and use for a templating system the same JS context that will be used in a JS module exported by the `html-loader` plugin?

In case of underscore/lodash templates it could be webpack's `require` to import/include some other portions of html; and finally the use of HtmlWebpackPlugin's context should allow to get direct access to generating page's data and resolve the original issue here.

[underscore-template-loader](https://github.com/emaphp/underscore-template-loader) has the idea I'm referring to ([code](https://github.com/emaphp/underscore-template-loader/blob/master/index.js#L118)). And HtmlWebpackPlugin ([code](https://github.com/jantimon/html-webpack-plugin/blob/main/lib/loader.js#L26-L33)) itself does this by default as well: compile a function from a template and let webpack run it to use the full context which is used for additional `require`s and accessing HWP's state/options.

@alexander-akait would very nice to hear your thoughts on that, what do you think? thanks!
