### ISSUE TITLE
Input type is removed and breaks css

### ISSUE THREAD

**Issue by devRoemer** [webpack-contrib/html-loader#323]
- Operating System: Windows
- Node Version: 12.18.3
- NPM Version: 6.3.0
- webpack Version: 4.44.1
- html-loader Version: >= 1.2.0 (tested also with 1.3.0)

### Expected Behavior
Inputs like this are not changed:
```
<input type="text" name="test">
```

### Actual Behavior
Type text is removed because it is browser default:
```
<input name="test">
```

### Code
Webpack-Config-Snippet
```js
            {
                test: /\.html$/,
                loader: 'html-loader',
                exclude: /(node_modules)/,
                options: {
                    attributes: {
                        list: [
                            { tag: 'img', attribute: 'src', type: 'src' },
                            { tag: 'img', attribute: 'data-srcset-1x', type: 'srcset' },
                            { tag: 'img', attribute: 'data-srcset-2x', type: 'srcset' },
                        ]
                    }
                }
            },
```
Full config: https://justpaste.it/4xbub

### How Do We Reproduce?
Use this default minimizer settings or the snippet above:
```js
            {
                test: /\.html$/,
                loader: 'html-loader',
                exclude: /(node_modules)/,
                options: {
                    minimize: {
                      caseSensitive: true,
                      collapseWhitespace: true,
                      conservativeCollapse: true,
                      keepClosingSlash: true,
                      minifyCSS: true,
                      minifyJS: true,
                      removeComments: true,
                      removeRedundantAttributes: true,
                      removeScriptTypeAttributes: true,
                      removeStyleLinkTypeAttributes: true,
                    },
                    attributes: {
                        list: [
                            { tag: 'img', attribute: 'src', type: 'src' },
                            { tag: 'img', attribute: 'data-srcset-1x', type: 'srcset' },
                            { tag: 'img', attribute: 'data-srcset-2x', type: 'srcset' },
                        ]
                    }
                }
            },
```

Add CSS:
```
input[type=text] {
    border: 1px solid red;
}
```

Result: The css gets ignored due to the removal of the type attribute.

Change removeRedundantAttributes to false.
Result: The input type is kept as it is and the css is still applied.

### Remarks
The behaviour has changed with Version 1.2.0 and the following commit:
https://github.com/webpack-contrib/html-loader/commit/03152b1d3b807a287d84302f6a9987ceb22d395c

Also see: https://github.com/webpack-contrib/html-loader/issues/35

Maybe removeRedundantAttributes should be disabled again. If not there should be a hint that there is a breaking change in the Changelog of version 1.2.0

**Comment by evilebottnawi** [comment]
Please use the issue template, `removeRedundantAttributes` is safe

**Comment by devRoemer** [comment]
@evilebottnawi 
In the referenced issue there are others with the same problem. As long as there is no css that relies on input[type="text"] it is safe that the minification removes the type="text" block of inputs. The browsers renders the input correctly.
Otherwise the change could destroy the layout of a page.

From my point of view it is a regression of #35. One could argue that removeRedundantAttributes can be disabled - what i did as a workaround. I am fine if it is left like this. But then there should be at least a hint in the Changelog states out that there are breaking changes due to minification changes...

**Comment by evilebottnawi** [comment]
@devRoemer please format the issue using the issue template and I will reopen

**Comment by devRoemer** [comment]
@evilebottnawi thanks. I've changed the description.

**Comment by evilebottnawi** [comment]
yep, bug, WIP
