### ISSUE TITLE
Allow URLs with absolute file paths

### ISSUE THREAD

**Issue by brettinternet** [webpack-contrib/html-loader#325]
- Operating System: Linux
- Node Version: `13.9.0`
- NPM Version: `6.14.7`
- webpack Version: `4.44.1`
- html-loader Version: `1.3.0`

### Feature Proposal

Allow URLs with an absolute file path.

```html
<img src="/home/bob/dev/myproject/images/tree.png" />
```

As far as I know, this is not currently possible:

> For urls that start with a /, the default behavior is to not translate them. If a root query parameter is set, however, it will be prepended to the url and then translated. ([source](https://github.com/webpack-contrib/html-loader#root))

### Feature Use Case

Deriving the relative path for sources within multiple nested HTML documents within a project can be tedious, especially if they're compiled from a templating method.

**Comment by evilebottnawi** [comment]
Why you need this? You can rewrite your code

**Comment by brettinternet** [comment]
I use a templating engine which compiles various templates within varying depths of relativity in the build directory. This is particularly an issue with partials. So a partial may reference an asset outside the build context such as `../src/images/pizza.png`, but within the build directory `build` only `/index.html` will correctly reference the asset and while `/product/pizza/index.html` will not, although both share the same partial. 
 
[This](https://github.com/webpack-contrib/html-loader/issues/318#issuecomment-682057024) doesn't work for me because the templating compilation occurs before webpack runs.

One workaround to is to pass relativity references around the partials. However, this can introduce tremendous clutter and becomes an issue attempting to use the compiled templates elsewhere, such as within an RSS feed because all relativity is ruined when `feed.xml` lives at the site root.

**Comment by brettinternet** [comment]
Another workaround I've thought of (but haven't tried yet) is to use the `preprocess` method in the loader options along with `posthtml`, [`posthtml-urls`](https://github.com/posthtml/posthtml-urls) and `path.relative` to rewrite the URLs into a relative state. Perhaps this is the most viable implementation.

However, I'm still under the impression that absolute paths are much easier to work with in a build process.

**Comment by evilebottnawi** [comment]
Please provide minimum reproducible test repo, we handle `/` server relative urls, but we will not handle absolute URLs, also this urls is invalid and you need to use `file://`

**Comment by evilebottnawi** [comment]
Also you can use `alias` for cases where you can rewrite original code

**Comment by brettinternet** [comment]
I will try the `preprocess` method.

Could you example what you mean by using `file://`? I haven't seen any documentation on its usage in Webpack.

**Comment by evilebottnawi** [comment]
`file://` it is browser protocol to handle locals files
