### ISSUE TITLE
"Process script and link tags" example doesn't work

### ISSUE THREAD

**Issue by frangio** [webpack-contrib/html-loader#329]
- Operating System: Arch Linux on Linux 5.8.13
- Node Version: 12.9.0
- NPM Version: 6 .14.8
- webpack Version: 5.1.3 (cli 4.1.0)
- html-loader Version: 1.3.2

### Expected Behavior

Script tag with a `src` attribute to a file that is processed by `file-loader` should emit the script tag with the `src` pointing to the asset generated by Webpack.

### Actual Behavior

The js file corresponding to the script tag is evaluated at bundle time.

`npx webpack` fails with:

```
ERROR in ./src/file.html
Module build failed (from ./node_modules/extract-loader/lib/extractLoader.js):
src/script.file.js:1
(function (exports, require, module, __filename, __dirname) { console.log(document);
                                                                          ^

ReferenceError: document is not defined
```

### How Do We Reproduce?

I've just copied the example from the readme verbatim.

https://github.com/frangio/repro-webpack-html-loader

This has been reported before as https://github.com/webpack-contrib/html-loader/issues/284, but since it's still unresolved with Webpack 5 I'm opening this issue.

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by evilebottnawi** [comment]
I will reopen this after you fix the problem

**Comment by frangio** [comment]
@evilebottnawi Done.

**Comment by evilebottnawi** [comment]
I see, but in `extract-loader` :disappointed: We can't fix it here :disappointed:

**Comment by evilebottnawi** [comment]
You can avoid using `document` in favor `this`/`globalThis`

**Comment by frangio** [comment]
I don't think that would fix the issue. The javascript shouldn't be evaluted at all.

The example should probably be removed from the readme.

**Comment by terox** [comment]
@frangio I am experiencing the same issues. 

The javascript is evaluated and it shouldn't be evaluated. The error comes from **extract-loader** but seems that there isn't any issue that notify that error recently. Then, is the example working with a specific version of ```extract-loader```? Could we resolve it with an other pipeline? @evilebottnawi

**Comment by evilebottnawi** [comment]
Please open an issue in `extract-loader` repo, I don't know why evaluate this, if they need this, they should provide document object

**Comment by alexander-akait** [comment]
Let' close in favor https://github.com/webpack-contrib/html-loader/issues/259, we still not support some edge cases for `style` and `script` tags, we need improve this
