### ISSUE TITLE
Are there any complete examples?

### ISSUE THREAD

**Issue by john01dav** [webpack-contrib/html-loader#335]
Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
In the README.md of this repository, some code blocks are given that document how to use this tool, but as I'm new to webpack, I'm not quite sure how to use them and when I try it doesn't work (the way in which it fails is unimportant to this issue). As such, it would be helpful to see a complete example so that I can very quickly and easily see everything that is needed, where nothing is implied. Such implication-filled documentation as is in README.md may work for someone who is more experienced with webpack, but there is no reason to limit this tool to those who fit in that category.

### Your Proposal for Changes
I propose that a complete, if basic, example of posthtml with multiple HTML files be created if needed and then linked near the top of README.md.

**Comment by evilebottnawi** [comment]
> In the README.md of this repository, some code blocks are given that document how to use this tool, but as I'm new to webpack, I'm not quite sure how to use them and when I try it doesn't work (the way in which it fails is unimportant to this issue). 

Please read our documentation https://webpack.js.org/

> I propose that a complete, if basic, example of posthtml with multiple HTML files be created if needed and then linked near the top of README.md.

Please open an issue in `posthtml-loader` or `posthtml` repo, we don't use this
