### ISSUE TITLE
// Module var code = "

### ISSUE THREAD

**Issue by firestar300** [webpack-contrib/html-loader#355]
Hello !

- Operating System: Mac OS Big Sur 11.2.1
- Node Version: 12.18.3
- NPM Version: 6.14.6
- webpack Version: 4.41.6
- html-loader Version: 1.3.2

### Expected Behavior
The import should return a valid HTML code.

### Actual Behavior
The import returns stringify JS code that contains a variable and the HTML.
![Capture d’écran 2021-02-12 à 10 52 00](https://user-images.githubusercontent.com/2543936/107754019-2c544280-6d21-11eb-9224-e06cab15cf80.png)

### Code
I use Storybook to add additonnal Webpack rules.
```js
const path = require('path')

module.exports = {
  'stories': [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  'addons': [
    ...
  ],
  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    // Make whatever fine-grained changes you need
    config.module.rules.push({
      test: /\.html$/,
      use: [
        {
          loader: 'html-loader',
          options: {
            minimize: true,
          }
        }
      ]
    });

    // Return the altered config
    return config;
  },
}
```

```js
import { createHeader } from './Header'
import Page from './Page.html'

export const createPage = ({ user, onLogout, onLogin, onCreateAccount }) => {
  const div = document.createElement('div')
  div.classList.add('dev-page')
  const article = document.createElement('article')

  const header = createHeader({ onLogin, onLogout, onCreateAccount, user })
  article.appendChild(header)

  article.insertAdjacentHTML('beforeend', Page)

  return article
}

```

```html
<div class="hello"><h1>Hello World!</h1></div>
```

Dunno if it's a bug with my current version of Webpack / HTML Loader or a missed parameter. Thanks for help.

**Comment by alexander-akait** [comment]
Sorry, something wrong with configuration, as you can see somethings breaks exports, I don't say what is wrong because you don't provide reproducible test repo

**Comment by firestar300** [comment]
Here we go : https://github.com/firestar300/html-loader-issues-355

**Comment by alexander-akait** [comment]
How I can redocue? Running `yarn bootstrap` doesn't reproduce the problem, to be honestly it looks like you apply `html-loader` twice, storybook always added `html-loader`, can you try to remove it from your configuraiton?

**Comment by firestar300** [comment]
That's it... Thank you and sorry for the waste of time. I remove the repo.
