### ISSUE TITLE
Angular2 directives <*ng-if="octocat"> breaks when prod

### ISSUE THREAD

**Issue by shprink** [webpack-contrib/html-loader#36]
When running webpack in prod mode `-p` an error occurs when using directives such as `*ng-if` because of the `*` that somehow breaks html-loader.

```
ERROR in ./lib/components/http/index.html
Module build failed:
 @ ./lib/components/http/index.ts 34:22-45
```

If you want to test you can clone https://github.com/shprink/angular2-nobullshit-boilerplate/ and change the raw loader by the html loader in this line: https://github.com/shprink/angular2-nobullshit-boilerplate/blob/master/webpack.config.js#L28

**Comment by geraldlrh** [comment]
I use other js template engine，and has the same problem，html cannot handle attr like this:
```html
<li {{if repayBankCardId === value.cardId}} class="on autoon" {{/if}} txt="{{value.bankOrgName}}" val="{{value.cardId}}">
```
Any good ideas?

**Comment by chrisnicola** [comment]
Have you tried fiddling with the minifier settings?

**Comment by NomNomCameron** [comment]
@chrisnicola I experience the same problem I believe when using Vue.js' native directives. How can we adjust the minification accordingly so special characters like `@` and `:` in attributes don't cause the entire module build to fail?

**Comment by chrisnicola** [comment]
You should look at the options listed here: https://www.npmjs.com/package/html-minifier

The html-loader enables the following by default:

```
			"removeComments",
			"collapseWhitespace",
			"collapseBooleanAttributes",
			"removeAttributeQuotes",
			"removeRedundantAttributes",
			"useShortDoctype",
			"removeEmptyAttributes",
			"removeOptionalTags"
```

You can set the option in the query strying `html?removeOptionalTags=false` for example.

**Comment by schippie** [comment]
@chrisnicola I tried the above but it does not work. I even went as far as overwriting the index.js configuration line 74 to change true to false which also did not work. 

I am not sure what causes the above problems i only know its quite frustrating. 
The only way it seems to be possible is through customAttrAssign within htmlMinifier but that would require a lot of configuration i think ( and you cannot do that through the query vars i am guessing).

**Comment by schippie** [comment]
@shprink What i currently do within the webpack configuration for production:

```{
                test: /\.html$/,
                loader: 'html?minimize=false'
            }```

This prevents any errors while building at least though it does not minify the HTML

**Comment by shprink** [comment]
cool thanks for sharing!

**Comment by chrisnicola** [comment]
So to deal with this you need to use the custom attributes options. I'm not sure if there is currently a way to do this with the query string though as it is expects a regex.

See: http://perfectionkills.com/html-minifier-revisited/ for more details.

Let me know if you can make this work with the query string. If not I can probably put together a pull request to fix this for Angular2.

**Comment by uglow** [comment]
I've [documented a configuration](https://github.com/angular/angular/issues/7295#issuecomment-189063411) that seems to work with Angular2.0.0-beta6

**Comment by michael-ciniawsky** [comment]
@uglow Could you elaborate futher on this please? Especially, what specific minimze options break angular components

**Comment by uglow** [comment]
The specific config options which break Angular 2 templates are:

```
  removeAttributeQuotes: false,   //<-- preserve attribute quotes
  caseSensitive: true,    //<--- to preserve attributes like ngIf
  customAttrSurround: [ [/#/, /(?:)/], [/\*/, /(?:)/], [/\[?\(?/, /(?:)/] ],  // <--- preserve * in *ngIf
  customAttrAssign: [ /\)?\]?=/ ]     //<--- not sure what this is for
```

I can't recall where I found this, but search the interwebs and you will find an earlier reference to this configuration.

**Comment by michael-ciniawsky** [comment]
@uglow Thx yep sure in progress, just gathering info where I can and you investigated already 😛
