### ISSUE TITLE
include of favicon in `link` tag with `href` fails when path begins with `../`

### ISSUE THREAD

**Issue by lopopolo** [webpack-contrib/html-loader#360]
- Operating System: Arch Linux
- Node Version: v14.15.4
- NPM Version: 6.14.11
- webpack Version: 5.21.2
- html-loader Version: 2.0.0

### Expected Behavior

`html-loader` can load resources outside of the current directory by traversing ".." directory components into a parent directory.

### Actual Behavior

Compilation failure

#### index.html

```html
    <%= require('html-loader!./partials/favicons.html') %>
```

### partials/favicons.html

```html
<!-- favicons -->
<link rel="apple-touch-icon" sizes="180x180" href="../assets/favicons/apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="32x32" href="../assets/favicons/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="../assets/favicons/favicon-16x16.png" />
<link rel="icon" type="image/png" href="../assets/favicons/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="../assets/favicons/android-chrome-512x512.png" sizes="512x512">
<link rel="manifest" href="../assets/favicons/site.webmanifest" />
<link rel="mask-icon" href="../assets/favicons/safari-pinned-tab.svg" color="#b91d47" />
<link rel="shortcut icon" href="../assets/favicons/favicon.ico">
<meta name="msapplication-tilecolor" content="#b91d47" />
<meta name="msapplication-tileimage" content="../assets/favicons/mstile-150x150.png">
<meta name="theme-color" content="#ffffff" />
```

### How Do We Reproduce?

I don't have a reproducer since I worked around this by moving the asset directory to be on the same level as the partial. Upgrading to 2.0.0 has not been fun :(

**Comment by alexander-akait** [comment]
You need to change `href` on valid URL, or you can use `resolve.alias`, nothing to fix here, sorry, because you don't provide reproducible test repo I can't help your

**Comment by alexander-akait** [comment]
Try to use `<link rel="apple-touch-icon" sizes="180x180" href="/assets/favicons/apple-touch-icon.png" />`
