### ISSUE TITLE
"ReferenceError: URL is not defined" when using images in HTML Template and HtmlWebpackPlugin

### ISSUE THREAD

**Issue by benwilhelm** [webpack-contrib/html-loader#362]
- Operating System: MacOS 10.14.6
- Node Version: 14.5.0
- NPM Version: 6.14.5
- webpack Version: 5.22.0
- html-loader Version: 2.0.0

### Expected Behavior

When using `<img src="./static/my-image.jpg" />` and including a rule of type "asset/resource", I expect to see an image file emitted to my dist directory, and an `img` tag with correct source attribute in the generated HTML. (Using HTML template with HtmlWebpackPlugin and html-loader)

### Actual Behavior

With html-loader version 2.0, my build fails with `ReferenceError: URL is not defined`. Downgrading to html-loader@1.3.2 solves the problem and builds as expected.

### Code

Minimum reproduction here: https://github.com/benwilhelm/html-loader-bug-report

### How Do We Reproduce?

Clone the repository above, run 

```
npm install
node_modules/.bin/webpack --mode development
```

That will fail with the described error.

As I mentioned, downgrading html-loader to 1.3.2 should resolve the problem

**Thank you!**

**Comment by alexander-akait** [comment]
Duplicate https://github.com/jantimon/html-webpack-plugin/issues/1602
