### ISSUE TITLE
html-loader can not link images loaded by file-loader

### ISSUE THREAD

**Issue by shariult** [webpack-contrib/html-loader#368]
- Operating System: Windows 10
- Node Version: v14.15.5
- NPM Version: 6.14.11
- webpack Version: 5
- html-loader Version: 2.1.0

### Expected Behavior

After file-loader outputs images in the "outputPath", the path is exported in an image file in the dist directory. If you open the image as text you can see some code. Also html file contains the path of this invalid image.

### Actual Behavior

The image link should be in the html template instead an invalid image is linked. The invalid image contains some text like "webpack exports 'img/logo.png'". I don't actually remember.
html-loader@1.3.2 works very well.
### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
module: {
    rules: [
      {
        test: /\.html$/,
        exclude: /node_modules/,
        loader: "html-loader",
      },
      {
        test: /\.(gif|jpe?g|tiff|a?png|webp|bmp|svg|tiff?)$/,
        exclude: [
          /(node_modules|bower_components)/,
          path.resolve(__dirname, `${appPath.scssDir}`),
        ],
        loader: "file-loader",
        options: {
          name: "[name].[ext]",
          outputPath: "img",
        },
      },
    ],
  },
```

### How Do We Reproduce?
Just load images using file-loader and use html-loader to load html template.

**Comment by bigskillet** [comment]
Try setting `esModule` to `false`:
```
loader: 'html-loader',
options: {
  esModule: false
}
```

**Comment by alexander-akait** [comment]
`file-loader` is deprecate for webpack v5, it is in readme for all loaders

> How Do We Reproduce?

Sorry, not enough to reproduce the problem, we have a lot of tests for `sources`, so please provide full reproducible test repo, if you need a help, won't fix right now

**Comment by nihey** [comment]
I faced the same issue, it seems Webpack's [Asset Modules](https://webpack.js.org/guides/asset-modules/) is somehow conflicting with `file-loader` (I'm not sure though)

But in anyway, adding a `dependency: { not: ['url'] }`, disabling Webpack's Asset Modules for `file-loader` fixed my issue:

```javascript
{
  test: /\.(png|jpe?g|svg|ttf|woff2?|mp3|ogg)$/,
  use: "file-loader",
  dependency: { not: ['url'] },
}
```

**Comment by alexander-akait** [comment]
@nihey Why do you use `file-loader`?

**Comment by nihey** [comment]
@alexander-akait I could not manage to get my build working with `asset/resource` during an webpack upgrade. But it was actually my fault (another thing was broken on my configurations), changing the rule to:

```
{
  test: /\.(png|jpe?g|svg|ttf|woff2?|mp3|ogg)$/,
  type: "asset/resource",
}
```

Actually solved the issue and I can now remove `file-loader` from my project's dependencies.

**Comment by alexander-akait** [comment]
Great, avoid using `file-loader` and `url-loader`, less deps === less problems
