### ISSUE TITLE
Regression in /favicon.ico handling (1.3.2 -> 2.x)

### ISSUE THREAD

**Issue by nil4** [webpack-contrib/html-loader#369]
- Operating System: Windows 10 (20H2)
- Node Version: 15.9.0
- NPM Version: 7.5.4
- webpack Version: 5.23.0
- html-loader Version: 2.1.0

### Expected Behavior

Upgrading from `html-loader@1.3.2` to `html-loader@2.x` handles `/favicon.ico` references in the template HTML file correctly.

### Actual Behavior

Upgrading from `html-loader@1.3.2` to `html-loader@2.1.0` breaks `/favicon.ico` references in the HTML template.

### Code

https://github.com/nil4/html-loader-2.x-regression

### How Do We Reproduce?

In https://github.com/nil4/html-loader-2.x-regression a trimmed-down repro is provided for a regression we observed when upgrading from `html-loader@1.3.2` to `2.0.0` and `2.1.0`. 

In the repo there are two commits:
- https://github.com/nil4/html-loader-2.x-regression/commit/5adcc5a9feaf21511437f36e1d419ac0dc1295d3 is the 'good' state, with `html-loader@1.3.2` and `html-webpack-plugin@5.0.0`, which works as expected
- https://github.com/nil4/html-loader-2.x-regression/commit/7ccb5bce94f85539dfc09f21486f491a61870c95 upgrades `html-loader` to `2.1.0` and `html-webpack-plugin` to `5.2.0`, and the regression is visible

Note that [src/app.html](https://github.com/nil4/html-loader-2.x-regression/blob/main/src/app.html) references `/favicon.ico` in two places, namely:
```html
<link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
<img src="/favicon.ico" alt=""/>
```

Expected behavior is that, after bundling, the `dist/index@hash.html` file produced should include versioned references similar to:
```html
<link href="/favicon@hash.ico" rel="shortcut icon" type="image/x-icon" />
<img src="/favicon@hash.ico" alt=""/>
```

To get a baseline for the regression, clone the repo and run:
- `git checkout 5adcc5a9feaf21511437f36e1d419ac0dc1295d3`  (initial/good state, with `html-loader@1.3.2`)
- `npm i && npm run bundle-prod`

At this point, `dist/index@hash.html` contains references to `/favicon@hash.ico`, as expected. ✔
On my machine I got `dist/index@4d638fef.html` with:
```html
<link rel="shortcut icon" href="/favicon@f3262202.ico" type="image/x-icon" />
<img src="/favicon@f3262202.ico" alt=""/>
```
The `dist/favicon@f3262202.ico` file contains the binary data for the icon, as expected. ✔

To now reproduce the regression, run:
- `git checkout 7ccb5bce94f85539dfc09f21486f491a61870c95` (upgrade to `html-loader@2.1.0` and `html-webpack-plugin@5.2.0`)
- `npm i && npm run bundle-prod`

Examine `dist/index@hash.html`, expecting the same kind of references to `/favicon@hash.ico` as before. 
Observe that `/long-hex-hash.ico` references are present instead: ⚠
```html
<link rel="shortcut icon" href="/a4b63416ae2ca2ea0ce1.ico" type="image/x-icon" />
<img src="/a4b63416ae2ca2ea0ce1.ico" alt=""/>
```
On my machine, a file `dist/favicon@f3262202.ico` is also created, and it contains the binary data for the icon, as expected. ✔
But the HTML file produced does not reference that. Instead, `dist/a4b63416ae2ca2ea0ce1.ico` is referenced, which appears to be an ES module with the following content:
```js
module.exports = __webpack_public_path__ + "favicon@f3262202.ico";
```

Needless to say, this is an invalid image file, and when the browser downloads this 'image' it is unable to decode it. 

This appears to be a functional regression, and it is reproducible with either `html-loader@2.0.0` or `@2.1.0`.

There are probably some NPM dependencies in the repro code that aren't strictly necessary, and I apologize for that! This was simplified from a large application, and I tried to keep all things equal, except trimming down the app-specific code to the minimum necessary to illustrate the issue.

**Comment by alexander-akait** [comment]
`file-loader` is depreacted for webpack v5, new verison of `html-loader` uses `new URL` syntax, so you need to migrate on https://webpack.js.org/guides/asset-modules/, if you want to still use `file-loader` you need to set `esModule: false` for `html-loader`
1. Solutions with migration

```js
{
  test: /\.(ico|eot|otf|svg|ttf|woff(2)?)$/,
  type: 'asset/resource',
  generator: {
    filename: '[name]@[contenthash:8][ext]'
  },
  include: [
    srcDir,
    path.join(npmDir, 'font-awesome', 'fonts'),
  ],
}
```

2. Solution without migration

```js
{ 
  loader: 'html-loader', 
  options: { 
    sources: { 
      list: [
        { tag: 'link', attribute: 'href', type: 'src' }, 
        { tag: 'img', attribute: 'src', type: 'src' },
      ]
    },
    esModule: false,
    minimize: false,
  }
}
```

**Comment by alexander-akait** [comment]
Also for importing assets you can use `new URL('./image.png', import.meta.url)` syntax, it will work on Node.js, browser, deno and other envs where ES modules are supported, it is new way for bundling assets

**Comment by nil4** [comment]
@alexander-akait thank you very much for the examples provided -- I really appreciate them! Applying the solution with migration resolved the issue and simplified the dependencies as a nice side-benefit.

**Comment by alexander-akait** [comment]
less deps - less problems
