### ISSUE TITLE
2.x compile html with img error

### ISSUE THREAD

**Issue by longSir666** [webpack-contrib/html-loader#374]
ERROR:

 __webpack_require__.b = require("url").pathToFileURL(__filename);
                                                                 ^
  ReferenceError: __filename is not defined

  **version eg:**

    "file-loader": "^6.2.0",
    "html-loader": "^2.1.1",
    "html-webpack-plugin": "4.5.1",
    "html-withimg-loader": "^0.1.16",
    "url-loader": "^4.1.1",
    "webpack": "5.12.0",
    "webpack-cli": "4.5.0"

**Comment by alexander-akait** [comment]
Update `html-webpack-plugin` to v5
