### ISSUE TITLE
can't find module introduced in patch from 2.1.0 to 2.1.1 

### ISSUE THREAD

**Issue by skoblenick** [webpack-contrib/html-loader#375]
- Operating System: `MacOS Catalina 10.15.7`
- Node Version: `v14.16.0`
- NPM Version: `v7.6.1`
- webpack Version: `^5.24.3`
- html-loader Version: `2.1.0` + `2.1.1`

### Expected Behavior

Build would bundle resources without errors when bundling html,css,jpg as demonstrated in examples on webpack.js.org:

- https://webpack.js.org/loaders/html-loader/#export-into-html-files
- https://webpack.js.org/loaders/html-loader/#cdn
- https://webpack.js.org/loaders/html-loader/#process-script-and-link-tags
- https://webpack.js.org/loaders/extract-loader/#extracting-the-indexhtml
    - documented api for extract-loader has changed since document was written, but isn't an issue here. only referenced as how the code below was derived

### Actual Behavior

Build fails to bundle with `html-loader@2.1.1`
Build compiles and generates artifacts with `html-loader@2.1.0` 

### Code

See https://github.com/skoblenick/webpack-experiment

### How Do We Reproduce?

Instructions provided in the repository linked above in code

**Comment by alexander-akait** [comment]
Bug in `extract-loader`... they do not support `file:///` URLs...
