### ISSUE TITLE
TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by Soviut** [webpack-contrib/html-loader#378]
- Operating System: Ubuntu (running in WSL2)
- Node Version: 14
- NPM Version: 6.14.8
- webpack Version: 4.46.0
- html-loader Version: 2.1.2

### Expected Behavior

I'm using the Nuxt framework and am trying to import a markdown file into my translation file. I installed the markdown-loader and the html-loader which are both required. I expected to be able to import the markdown file, have it processed to html, then have the html turned into a string in my javascript.

### Actual Behavior

I keep getting the following error `TypeError: this.getOptions is not a function`.

```
web_1  |  ERROR  in ./locales/testing.md
web_1  | 
web_1  | Module build failed (from ./node_modules/html-loader/dist/cjs.js):
web_1  | TypeError: this.getOptions is not a function
web_1  |     at Object.loader (/src/node_modules/html-loader/dist/index.js:17:27)
web_1  | 
web_1  |  @ ./locales/en.js 7:0-35 10:11-18
web_1  |  @ ./locales lazy ^\.\/.*$ include: \.(js|ts|json|ya?ml)$ namespace object
web_1  |  @ ./.nuxt/nuxt-i18n/utils.js
web_1  |  @ ./.nuxt/nuxt-i18n/plugin.main.js
web_1  |  @ ./.nuxt/index.js
web_1  |  @ ./.nuxt/client.js
web_1  |  @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

### Code

```js
      config.module.rules.push({
        test: /\.md$/,
        use: [
          {
            loader: 'html-loader',
          },
          {
            loader: 'markdown-loader',
          },
        ],
      })
```

**en.js** (translations)

```js
import testing from './testing.md'

export default {
  shouldBeMarkdown: testing,
}
```

Trying to import an html file directly produced the same issue

```js
import testing from './testing.html'
```

However, I _was_ able to import without error using the raw-loader

```js
import testing from '!!raw-loader!./testing.md'
```

**Comment by Soviut** [comment]
I wound up changing my webpack config to use raw-loader since all I really needed was the raw html string from markdown-loader. 

```js
      config.module.rules.push({
        test: /\.md$/,
        use: [
          {
            loader: 'raw-loader',
          },
          {
            loader: 'markdown-loader',
          },
        ],
      })
```

Still, this seems worth reporting since every example shows markdown-loader used with html-loader.

**Comment by XingtianLiu** [comment]
I  think ``webpack@4`` is not supported by v2, my ``devDependencies`` can work:

```x
"html-loader":"^1.1.0",
"webpack": "^4.40.2",
"webpack-cli": "^3.3.9"
```

**Comment by alexander-akait** [comment]
You need webpack v5 to use latest version, please read CHANGELOG

**Comment by Soviut** [comment]
Ah, I see. I even tried using older versions of html-loader but didn't try anything lower than 2.0.
