### ISSUE TITLE
Root relative path is not resolved using the resolve.roots

### ISSUE THREAD

**Issue by axibyte** [webpack-contrib/html-loader#381]
According to the documentation at https://github.com/webpack-contrib/html-loader#roots server-relative URLs (starting with '/') should be resolved if resolve.roots is specified. But this is not working.

- Operating System: Windows 10
- Node Version: 12.18.0
- NPM Version: 6.14.4
- webpack Version: 5.30.0
- html-loader Version: 2.1.2

### Expected Behavior

Resolve server-relative URL by using the root specified by resolve.roots

### Actual Behavior

Error is raised: Cannot find module '/img/image1.jpg' from [...]

### Webpack Config
<pre>
resolve: {
          roots: [
                path.resolve(__dirname, 'src')
          ]
}
</pre>

<pre>
{
                  loader: "html-loader",
                  options: {
                      esModule: false,
                      minimize: false,
                      sources: {
                          list: [
                              {tag: 'img', attribute: 'src', type: 'src'},
                          ]
                      }
                 }
}
</pre>

### HTML File:
<pre>
    &lt;img src="/img/image1.jpg"/&gt;
</pre>

### Directory Structure:
<pre>
project
    src
       img
          image1.jpg
    webpack.config
</pre>

**Comment by alexander-akait** [comment]
Can you provide simple repo? Works fine locally...
