### ISSUE TITLE
How to trigger re-compile if partial changed?

### ISSUE THREAD

**Issue by mattp0123** [webpack-contrib/html-loader#386]
I'm using this example from [Webpack doc](https://webpack.js.org/loaders/html-loader/#templating).

This is my Webpack config:
```javascript
// in my webpack.config.js
const fs = require('fs');
const Handlebars = require('handlebars');

const navPartial = fs.readFileSync('./src/partials/nav.html', 'utf-8');

const myConfig = {
  ...
  {
    test: /\.html$/i,
    loader: 'html-loader',
    options: {
      preprocessor: (content, loaderContext) => {
        try {
          handlebars.registerPartial('nav', navPartial);

          return handlebars.compile(content)(myData);
        } catch (err) {
          loaderContext.emitError(error);

          return content;
        }
      },
    },
  },
  ...
}
```
If I make some changes to the nav partial html, the file won't be re-processed in webpack dev server watch mode.
Is there any proper way to do that?

**Comment by alexander-akait** [comment]
You need `loaderContext.addDependecy('/absolute/path/to/file.ext')`

**Comment by mattp0123** [comment]
> You need `loaderContext.addDependecy('/absolute/path/to/file.ext')`

@alexander-akait Thanks for the reply!
I got this error message:
```
Module build failed (from ./node_modules/html-loader/dist/cjs.js):
TypeError: loaderContext.addDependecy is not a function
```

**Comment by alexander-akait** [comment]
oh, sorry, typo, `loaderContext.addDependency("/absolute/path/to/file.ext")`

**Comment by mattp0123** [comment]
It works. Many thanks!
