### ISSUE TITLE
when to publish tag on 'fix(getOptions): deprecation change'

### ISSUE THREAD

**Issue by zhijs** [webpack-contrib/html-loader#389]
- Operating System: mac os
- Node Version: v10.16.0
- NPM Version:  6.9.0
- webpack Version: 4.41.28
- html-loader Version: 2.1.2

### Expected Behavior
build success when import .html file

### Actual Behavior
got error:

ERROR in ./dist/index.html
Module build failed (from ./node_modules/html-loader/dist/cjs.js):
TypeError: this.getOptions is not a function

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by alexander-akait** [comment]
You need webpack v5 to use the latest version of `html-loader`
