### ISSUE TITLE
Style attribute with expansion variable is omitted when minimized

### ISSUE THREAD

**Issue by ekeydar** [webpack-contrib/html-loader#392]
- Operating System: ubuntu 20.04
- Node Version: 16.3.0
- NPM Version: 7.15.1
- webpack Version: 5.45.1
- html-loader Version: 2.1.2

### Expected Behavior

style attribute should not be modified

### Actual Behavior

style attribute is modified, and we loose the variable

### Code

https://gist.githubusercontent.com/ekeydar/8c91ff74678b16eefdedf524fd7a65e3/raw/db9b54ac74079d1b17c535419bf50789f057f375/webpack.config.js

### index.js

```js
import html from './file.html';

function main() {
    console.log('=====================================');
    console.log(html);
    console.log('=====================================');
}

window.onload = main;

```

### file.html

```html
<div style="color: {{ 'orange' }}; font-weight: {{ 'bold' }};">
  {{ g.name }}
</div>
``` 

### How Do We Reproduce?

The index.js importing the file.html and log its content to the console.
You can see when minimized, the style attribute lack some of its content.
The output is:
```<div style="color:{};"> {{ g.name }} </div>```

**Comment by alexander-akait** [comment]
Because you have non standard HTML, in this case you need to change options for minimize

**Comment by ekeydar** [comment]
OK. Thanks. Fair enough.
