### ISSUE TITLE
After upgrading from v1.3.2 to v2.1.2, <%= require("html-loader!x.html") %> is not available.

### ISSUE THREAD

**Issue by chishuix** [webpack-contrib/html-loader#399]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

When I use the v1.3.2 version, using this code can get the correct display.

`<%= require("html-loader!/src/components/_topbar.html") %>`

I checked the document before upgrading the version, and the wording has not changed, so I upgraded the version. 

But when I upgraded to v2.1.2, using the same code showed ` [object Module]`.

Now, I need some help, thank you.

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack-contrib/html-loader/issues/291
