### ISSUE TITLE
Which tag attribute combinations should be converted?

### ISSUE THREAD

**Issue by fernandoacorreia** [webpack-contrib/html-loader#4]
[Opened for discussion](https://github.com/webpack/webpack/issues/154#issuecomment-33229771) by @sokra.

**Comment by tborychowski** [comment]
`Default: attrs=img:src` this is the most ridiculous default ever!
I just wasted an hour trying to figure out the no-error, and why does my webpack want to `require` an image, which is not local...
Thanks!

**Comment by jhnns** [comment]
@tborychowski why are you using the html-loader? If you don't want webpack to recognize assets in your HTML, use the raw-loader which treats the HTML just as strings without parsing it as HTML.

**Comment by tborychowski** [comment]
@jhnns, that's a brilliant idea!
I would have found that myself if the docs were a bit less confusing :-)

- `html-loader`: Exports HTML as string. HTML is minimized when the compiler demands.
- `raw-loader`: A loader for webpack that lets you import files as a string.

🤔 what was I looking for? - HTML, possibly with minification!

But I know I should have RTFM :-)
Stil think that this should not be enabled by default though!
It's a great feature, but when I think of "loading html" - I would never in my life think of loading all of the referenced images...

**Comment by jhnns** [comment]
I think, that heavily depends on the use case. If you're building a SPA with HTML templates, this behavior is probably desired (otherwise you would need to keep track of "static" assets like images with a separate build process). However, I agree that there are also use cases where this is kind of surprising.
