### ISSUE TITLE
Parse errors with html content containing <

### ISSUE THREAD

**Issue by niemyjski** [webpack-contrib/html-loader#400]
- Operating System:  macOS 11.5.2, Windows 10
- Node Version: 16.6.2
- NPM Version: 7.20.3
- webpack Version: 5.50.0
- html-loader Version: 2.1.2

We upgraded from 0.4.5 to 2.1.2 and I'm thinking this has to do with parse5. Binding syntax below is vuejs. Is there a way to escape angle brackets inside of a binding expression? I know for markup I can escape with HTML entities, but not for expressions. Odd thing is I don't see this behavior in non prod mode.

### Expected Behavior

```html
<div>{{ idx < (array.length - 1) && idx < 5 ? ',' : '' }}</div>
```

```html
<div><{{ replyToEmailAddress }}></div>
```

### Actual Behavior

```
Module Error (from ./node_modules/html-loader/dist/cjs.js):
Parse Error: < (array.length - 1) && idx < 5 ? ',' : '' }}

...

Module Error (from ./node_modules/html-loader/dist/cjs.js):
Parse Error: <{{ replyToEmailAddress }}>

```

### Code

```js
        {
          test: /\.html$/,
          loader: 'html-loader'
        }
```

### How Do We Reproduce?

Copy the html above and put it in an html file and then try to build with production mode on.

**Comment by alexander-akait** [comment]
Because it is HTML loader, your code is not HTML and do not valid, so parser failed

**Comment by niemyjski** [comment]
Specifying < in inner text is valid html....

**Comment by alexander-akait** [comment]
We don't have magic here https://github.com/webpack-contrib/html-loader/blob/master/src/plugins/sources-plugin.js#L13

**Comment by alexander-akait** [comment]
If parser can't parse it, we can't work, if you think it is valid code please open an issue in `parse5` package, we can't fix it here
