### ISSUE TITLE
this.getOptions is not a function

### ISSUE THREAD

**Issue by YounessBird** [webpack-contrib/html-loader#401]
- Operating System:macOS
- Node Version: 12.13.0
- NPM Version: 6.12.0
- webpack Version: 4.5.0
- html-loader Version: from v2.0.0 to v2.1.2 

### Expected Behavior

Compile without errors

### Actual Behavior

Failed to compile with 1 errors

### Code

```js
 ERROR in ./popup.html (./node_modules/html-webpack-plugin/lib/loader.js!./popup.html)
    Module build failed: TypeError: this.getOptions is not a function
        at Object.loader (/****** /node_modules/html-loader/dist/index.js:17:27)
```

###  How Do We Reproduce?
use webpack 4.5.0 with html-loader Version: from v2.0.0 to v2.1.2 
npm run dev

###  Potential solution
npm install --save-dev  html-loader@1.3.2

**Comment by alexander-akait** [comment]
You need webpack v5 to use the latest version, please consider to update webpack
