### ISSUE TITLE
params “source: false”  is  falied

### ISSUE THREAD

**Issue by KID-1912** [webpack-contrib/html-loader#402]
I have set params 
`options: {
sources: false,
}`
but error message:

ERROR in   Error: Child compilation failed:
  Module parse failed: Unexpected token (3:44)
  File was processed with these loaders:
   * ./node_modules/html-loader/dist/cjs.js
   * ./node_modules/html-loader/dist/cjs.js
  You may need an additional loader to handle the result of these loaders.
  | // Imports
  | import ___HTML_LOADER_GET_SOURCE_FROM_IMPORT___ from "../node_modules/html-loader/dist/runtime/getUrl.js";
  > var ___HTML_LOADER_IMPORT_0___ = new URL("/"http://192.168.3.46:8081/mobile/game_mario/images/start/btn_tag.png/"/",   import.meta.url);
  | var ___HTML_LOADER_IMPORT_1___ = new URL("/"http://192.168.3.46:8081/mobile/game_mario/images/start/btn_my_prize.png  /"/", import.meta.url);
  | var ___HTML_LOADER_IMPORT_2___ = new URL("/"http://192.168.3.46:8081/mobile/game_mario/images/start/btn_rank.png/"/"  , import.meta.url);:

**Comment by KID-1912** [comment]
How do I fix it?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
