### ISSUE TITLE
remove documentation of use cases involving extract-loader 

### ISSUE THREAD

**Issue by calebTree** [webpack-contrib/html-loader#404]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Is it a wild goose chase to document a use case with `extract-loader` when that is obsolete?

### Your Proposal for Changes
Remove obsolete mentions of `extract-loader`

**Comment by calebTree** [comment]
Wonderful.

**Comment by langri-sha** [comment]
What is the alternative, though?

**Comment by langri-sha** [comment]
:point_up: ok, looks like for CSS [experiements.css](https://webpack.js.org/configuration/experiments/#experimentscss) seems to be a great direction.
