### ISSUE TITLE
about the Template7 {{js}}

### ISSUE THREAD

**Issue by hejianxian** [webpack-contrib/html-loader#41]
hello!

text.html

```
<a href="#" class=" {{js "this.type === \'page\' ? \'back\' : \'\'"}}"></a>
```

when i run build! this html cant load! but i can require this in webpack-dev-server!

my format does not comply with it?

Forgive my bad English.. = =!!

**Comment by michael-ciniawsky** [comment]
@hejianxian You still have this issue/still relevant ? Please provide more info about your setup (`wepack.config.js`)
