### ISSUE TITLE
Readd root as webpack resolve.roots does not allow conditionally resolve

### ISSUE THREAD

**Issue by rofrol** [webpack-contrib/html-loader#412]
### Feature Proposal

Readd root as webpack `resolve.roots` does not allow conditionally resolve.

`root` was removed in https://github.com/webpack-contrib/html-loader/pull/341.

### Feature Use Case

In `html-loader@0.5.1` I could have these rules:

```javascript
module.exports = {
  module: {
    rules: [
      {
        test: /\.pug/,
        exclude: [/[\/\\]product2[\/\\].*\.pug$/],
        use: [
          {
            loader: 'html-loader',
            options: {
              path.resolve(__dirname, 'public'),
            },
          },
        ],
      },
      {
        test: /[\/\\]product2[\/\\].*\.pug$/,
        use: [
          {
            loader: 'html-loader',
            options: {
            root: path.resolve(__dirname, '../', 'product2', 'public'),
            },
          },
        ],
      },
    ],
  },
}
```

Now I just have resolve.roots which does not allow me to conditionally resolve.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```bash
$ ./node_modules/.bin/webpack-cli info

  System:
    OS: Linux 5.10 NixOS 21.11 (Porcupine) 21.11 (Porcupine)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 7.35 GB / 31.19 GB
  Binaries:
    Node: 16.13.0 - /run/current-system/sw/bin/node
    Yarn: 3.0.0 - ~/mutable_node_modules/bin/yarn
    npm: 8.1.0 - /run/current-system/sw/bin/npm
  Browsers:
    Firefox: 95.0
  Monorepos:
    Yarn Workspaces: 3.0.0
  Packages:
    raw-loader: ^4.0.2 => 4.0.2 
```

**Comment by alexander-akait** [comment]
You don't need `root` and it was bad solution, webpack has own roots in `resolve.roots` https://webpack.js.org/configuration/resolve/#resolveroots and html-loader use them

**Comment by alexander-akait** [comment]
If you have different URLs in your each template, please fix your tool to generate valid URLs, we don't design to fix wrong generated `src`/etc
