### ISSUE TITLE
Suggest adding explicit support for framework templates

### ISSUE THREAD

**Issue by chrisnicola** [webpack-contrib/html-loader#42]
The current settings will break Angular 2 templates as well as templates for many other MVC frameworks. Rather than try to require uses to pass custom ignore regex's it would be better to have a framework query:

`html?framework=Angular2` or `html?framework=Ember`, etc that ensured the minification settings were safe by default for those frameworks. I'm happy to put together pull requests for Angular and Angular2.

http://perfectionkills.com/html-minifier-revisited/

**Comment by michael-ciniawsky** [comment]
@chrisnicola Still interested in this? PR highly welcome 😛
