### ISSUE TITLE
David and HTML Loader badges are broken

### ISSUE THREAD

**Issue by yadunandanbhat** [webpack-contrib/html-loader#430]
Documentation Is:
the html-loader and the david badges are broken.

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

See the below image.
![image](https://user-images.githubusercontent.com/54680617/164375875-7dbb3d0a-fa00-4307-816c-75931751bb65.png)
https://david-dm.org/webpack-contrib/html-loader is down (see [alanshaw/david#182](https://github.com/alanshaw/david/issues/182) and the "html-loader" is also broken
### Your Proposal for Changes
Remove david badge and update the html loader badge link

**Comment by alexander-akait** [comment]
PR welcome, you can send PRs without open issues, it is broken so let's remove

**Comment by yadunandanbhat** [comment]
will open a pr right away!

**Comment by yadunandanbhat** [comment]
There's also a image link that's broken. In the readme its "https://worldvectorlogo.com/logos/html5.svg" but it goes to "https://cdn.worldvectorlogo.com/logos/html5.svg", shall i update that too?

**Comment by yadunandanbhat** [comment]
I've opened a PR. Please accept the workflow and review the changes

**Comment by alexander-akait** [comment]
Fixed
