### ISSUE TITLE
ignoring noscript

### ISSUE THREAD

**Issue by echolimazulu** [webpack-contrib/html-loader#446]
### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
___
**Hello html-loader developers,**

Today I noticed that the content of supported tags wrapped in `noscript` is **completely ignored** and not available for creating html-loader imports to pass them to the next loader.

In my configuration before the html-loader, I also use posthtml-loader and the HTML elements inside `noscript` are **available to it**.

Please clarify if this loader behavior is expected and where to dig to fix or change this behavior.

Searching the repository turned up no results on this issue.

```
<noscript>
    <figure>
        <img src="/images/picture.jpg" alt="">
    </figure>
</noscript>
```

**html-loader version is 4.0.0**

**Comment by echolimazulu** [comment]
@alexander-akait Hello! I would be glad to know your vision on this issue. Thank you!

**Comment by echolimazulu** [comment]
Hello Alexander,

Thanks for your answer and thanks for the solution you suggested.

I tested this before, but unfortunately it didn't work. 

I mean the following changes that I made manually (`sources-plugin.js`):

```
const document = (0, _parse.parse)(html, {
    sourceCodeLocationInfo: true,
    scriptingEnabled: true
});
```

**Comment by alexander-akait** [comment]
hm, strange, looks like parse5 doesn't out AST (example https://astexplorer.net/#/gist/94acd53dbf527e8f8f735b5a28053ab0/3ba4cb0c2a734d61e0b868b6c3b879d509149472), that is why we don't handle it, when `scriptingEnabled` is `false` (not `true`) it should output contents of `noscript` as AST, not as text

**Comment by alexander-akait** [comment]
@echolimazulu I think we should add this option to our loader (so feel free to send a PR), and maybe set to `true` by default for the next major release

**Comment by echolimazulu** [comment]
@alexander-akait Good evening, Alexander,

I apologize for such a long response on my part. I proposed a solution in a **PR**: https://github.com/webpack-contrib/html-loader/pull/448

Unfortunately, I don't want to sign the Linux Foundation's CLS for signing the PR, besides, he fills out the form incorrectly with the specified e-mail, which I also reported to them.

Happy to help resolve this issue. If CLS is required and if my PR cannot be accepted without it, then you can pull this commit from the master branch of my repository. Thank you!

**Comment by echolimazulu** [comment]
@alexander-akait Good morning, Alexander,

With CLA, the issue is resolved, PR is ready for consideration. 

Glad to interact with you.

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/html-loader/pull/448, thank you again
