### ISSUE TITLE
Two Created Files

### ISSUE THREAD

**Issue by Vanillma** [webpack-contrib/html-loader#452]
### Actual Behavior

Hello
I have been trying to use Webpack for several days.
And I encountered a problem in configuring.
The problem is that during construction... two .js files are created... one with a complete hash and one with my desired name... after many tests, I realized that this behavior is created by the html loader.. And there is no way to turn it off... I opened an issue on the webpack page, but they don't know exactly where the problem is... But after a lot of testing, I found out that this behavior is caused by the html loader, and I don't know how turn off it.
I also asked a question on stackoverflow but no answer!

### How Do We Reproduce?

Please Clone
https://github.com/Vanillma/Ant
Go to root project
npm install
&
npm run build😬😁👍❤
&
Please see it 
https://github.com/webpack/webpack/discussions/16100
### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
![IMG_20220731_083419_810](https://user-images.githubusercontent.com/95992420/182077401-99e8f95b-6751-49c3-b1d4-32f5e06a0267.jpg)

**Comment by alexander-akait** [comment]
Please remove `<script src="index.js"></script>` from your HTML file, `HtmlWebpackPlugin` automatically insert `script` tag with URL, because your entyripoint is JS file, otherwise webpack handle one JS file in entrypoint and the send in `script` tag
