### ISSUE TITLE
need to support ES6 module

### ISSUE THREAD

**Issue by zhaxi** [webpack-contrib/html-loader#47]
I'm using webpack 2.0 beta, if I want to " import xx from 'x.css' ", then pass xx string to the template config(like template: xx), running will go wrong cause the build will be: " template: xx.default ", however htmlloader build will be : "module.exports=xx", not "module['default']=xx".

**Comment by donaldpipowitch** [comment]
Do you see an `Unexpected token .` error? I think this happens because of this. I `import xx from 'x.html';` and want to use it like that: `let foo = { xx }`. Which I guess compiles to something like `var foo = { xx: xx.default }`

**Comment by zhaxi** [comment]
Hi, thanks for replying. I would like to show you the code(Angular 2):
source:

import TabsHtmls from './bi-tabs.html';

@Component({
  selector: 'bi-tabs',
  template: TabsHtmls, // need to be string
  styles: [".bi-tabs{background-color:red}"],
  directives: [ROUTER_DIRECTIVES],
})

build :
var bi_tabs_html_1 = __webpack_require__(352);
	var BiTabs = (function () {
	    function BiTabs() {
	    }
	    __decorate([
	        core_1.Input(), 
	        __metadata('design:type', Array)
	    ], BiTabs.prototype, "biTabsConfigs", void 0);
	    BiTabs = __decorate([
	        core_1.Component({
	            selector: 'bi-tabs',
	            template: bi_tabs_html_1**.default**, // default
	            styles: [".bi-tabs{background-color:red}"],
	            directives: [router_1.ROUTER_DIRECTIVES],
	        }), 
	        __metadata('design:paramtypes', [])
	    ], BiTabs);
	    return BiTabs;
	})();

/* 352 */
/***/ function(module, exports, __webpack_require__) {

	module.e = "<div\n  hello\n</div>";

/***/ }

**Comment by laland** [comment]
looks like this PR does it https://github.com/webpack/html-loader/pull/97
it's already merged

**Comment by staeke** [comment]
cool...can you publish a new npm version so we can easily use this feature?

**Comment by laland** [comment]
@sokra can

**Comment by staeke** [comment]
looking forward to it!
