### ISSUE TITLE
Loading riot templates not working after upgrade

### ISSUE THREAD

**Issue by RanzQ** [webpack-contrib/html-loader#53]
I've been using this loader for [riot](http://riotjs.com/) templates and noticed that on upgrade from 0.4.0 to 0.4.2 all my onclick bindings stopped working. In riot I define them like this:

```
onclick="{ onClick }"
```

Any idea why it doesn't work anymore? I'd need those to stay unchanged in the loaded string.

**Comment by faller** [comment]
I came across the similar problem.

After updating from 0.3.0 to 0.4.3,  `wepack -p` transfrom

`<a href="<%= location %>/edit" target="_blank">edit</a>`

to 

`<a href="<%= location %> /edit" target="_blank">edit</a>`

which has an extra space after `%>`

**Comment by thaddeusmt** [comment]
This must be related too - updating from 0.3.0 to 0.4.0 my Underscore.js Templates started rendering with extra spaces inside the double quotes.

How it used to load:

`<a data-albumid="<%= id %>">`

How it loads now:

`<a data-albumid=" <%= id %> ">`

Resulting in a template rendering like this `<a data-albumid=" 1234 ">

**Comment by thaddeusmt** [comment]
Ah, probably related to the `html-minifier` dependency which has this bug: https://github.com/kangax/html-minifier/issues/506

**Comment by RanzQ** [comment]
Tried to fix this with the new config option:
```
  htmlLoader: {
    ignoreCustomFragments: [/\"?\{.*?\}\"?/]
  },
```
Seems to work but the build hangs when used with UglifyJsPlugin. Like in https://github.com/webpack/html-loader/issues/52 https://github.com/webpack/html-loader/issues/44 and https://github.com/webpack/html-loader/issues/50.

Does anyone have a solution how to configure this loader and the minifier properly?

**Comment by michael-ciniawsky** [comment]
@RanzQ You still have this regression?

**Comment by RanzQ** [comment]
@michael-ciniawsky I don't think so. Got one older project with v0.4.4 and it seems to work fine. I use UglifyJsPlugin in production. Not sure how and when this got fixed. 😆 

I use react and webpack 2 now so haven't used html-loader for a while.
