### ISSUE TITLE
ignoreCustomFragments do not behave correct. 

### ISSUE THREAD

**Issue by lili21** [webpack-contrib/html-loader#84]
my config

```
htmlLoader: {
  ignoreCustomFragments: [/\{\{.*?}}/],
  minimize: true
}
```

my html source code

```
...
<div class="tab-icon" style="background-color: {{ vm.bgcolor }}"></div>
...
```

the output html in browser 

```
...
<div class="tab-icon" style="background-color:" {{vm.bgcolor}}></div>
...
```

is it a bug ? or my config problem ?

**Webpack version:**
1.13.2

**HTML-Loader version:**
0.4.3

**Please tell us about your environment:**
OSX 10.x

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/html-loader/releases/tag/v1.0.0-alpha.0
