### ISSUE TITLE
Can't require separate package file; always includes current directory in path

### ISSUE THREAD

**Issue by joshunger** [webpack-contrib/html-loader#90]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.20

**HTML-Loader version:**
0.4.3

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
1. Create one package called "@company/stuff" with an image - @company/stuff/logo.png
2. Create a second package and reference the first package and try to require the image -

require('@company/stuff/logo.png');

**Expected/desired behavior:**
Works.

**Actual behavior:**

Module not found: Error: Can't resolve './@company/stuff/logo.png' in '...'

Is this supposed to work?

**Comment by tylerhsu** [comment]
An undocumented feature lets you use a tilde to treat a path as a module:

```require('~@company/stuff/logo.png')```

I wish this was the default behavior for non-absolute urls.  It's confusing if you ask me.

**Comment by michael-ciniawsky** [comment]
@joshunger Did @tylerhsu solution resolve the issue ?

**Comment by michael-ciniawsky** [comment]
`webpack >=4` && `html-loader >= 1.0.0` will support [this](https://github.com/webpack-contrib/html-loader/tree/next#npm-packages-modules) in the near future

**Comment by dietergeerts** [comment]
@michael-ciniawsky , that feature is not the same as `~`. It let's you get 1 thing from the package that is described in a property of package.json file. It should be documented that `~` is needed to require modules.
