### ISSUE TITLE
Can someone explain why every page request includes a call to xxxHTMLLINKxxx

### ISSUE THREAD

**Issue by devteamexpress** [webpack-contrib/html-loader#93]
We are trying to remove this request every time we load a page that is webpack based, can someone explain the purpose and how to remove it?

**Comment by dhardtke** [comment]
I am having the same issue and I would like to know where these requests are coming from:
```
"NetworkError: 404 Not Found - http://127.0.0.1:8081/xxxHTMLLINKxxx0.050223784609952030.6672830421714149xxx"
xxxHTML...4149xxx
"NetworkError: 404 Not Found - http://127.0.0.1:8081/xxxHTMLLINKxxx0.77954625930640240.6925719612229908xxx"
xxxHTML...9908xxx
"NetworkError: 404 Not Found - http://127.0.0.1:8081/xxxHTMLLINKxxx0.126923904508578820.8891797979233227xxx"
xxxHTML...3227xxx
"NetworkError: 404 Not Found - http://127.0.0.1:8081/xxxHTMLLINKxxx0.97765907948768430.986930958347531xxx"
xxxHTML...7531xxx
"NetworkError: 404 Not Found - http://127.0.0.1:8081/xxxHTMLLINKxxx0.068483218857035680.9269726279963828xxx"
xxxHTML...3828xxx
"NetworkError: 404 Not Found - http://127.0.0.1:8081/xxxHTMLLINKxxx0.99769072264016720.7875294046010128xxx"
```

**Comment by devteamexpress** [comment]
Let us know guys

**Comment by dhardtke** [comment]
Okay, I got it fixed (for me).

I am using https://github.com/tjoskar/ng2-lazyload-image and I was having a lot of HTML tags like these:
`<img src="" lazyLoad="/app/static/home/images/image_2.jpg">`

I had to remove the `src` attribute and now it's working. I don't know what you guys have that `randomIdent()` function for or why you iterate over all links and do something with them, but it's working for me now.

**Comment by thalida** [comment]
My team also ran into this issue during development, and we solved it by adding a valid src to our img tags. Placekitten to the rescue!

We tried changing from `<img src="" />` to `<img />` but, that also resulted the same: `xxxHTMLLINKxxx` error.

**Comment by michael-ciniawsky** [comment]
@devteamexpress @dhardtke @thalida Could someone elaborate on this futher ? We are working on a refactor of the loader and this is a topic discuss 😛  According to Tobias it's just a placeholder which webpack replaces with a Url Request. Is this useful/needed?

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/html-loader/releases/tag/v1.0.0-alpha.0
