### ISSUE TITLE
How to include meta information like width and height in img tags

### ISSUE THREAD

**Issue by jhnns** [webpack-contrib/html-loader#94]
**I'm submitting a feature request**

This is puzzling me for a long time and I would like to start a discussion about this. What do we need to change so that the html-loader is able to include the `width` and the `height` of an image. For instance:

``` html
<img src="path/to/image.jpg">
```

should become

``` html
<img src="9df78hdfh8dfhjd.jpg" width="400" height="200">
```

The motivation behind this is that the browser can proceed with layout calculations without waiting for the image to download. This should yield faster initial paints, especially on high-latency networks.

From my current POV, this makes sense in **every use-case** I thought of, but it may break code if there are already contradicting `width` and `height` attributes (but: who does that?).

However, the problem is: The file- and the url-loader only return a string. We have no way to pass meta information about the image. In order to not break existing code, we could change the file- and the url-loader to return an object instead of a string, but with a `toString()` method attached. This way, the object would be casted to a regular url in all situations where it is used as a string. But the html-loader would be able to use additional information about the referenced file.

This proposal could also allow other, new use-cases. What are your ideas?

@hemanth @d3viant0ne @sokra @TheLarkInn @bebraw

**Comment by bebraw** [comment]
Passing an object definitely sounds more versatile option to me. Maybe this could be architected so that it wouldn't break backwards compatibility. As you mention, doing `toString()` would most likely achieve this since string defines it too (returns string itself).

I guess the same mechanism could be used to implement adaptive images and all that (`img` `srcset` etc.).

**Comment by TheLarkInn** [comment]
At the cost of long builds could we calculate the dimensions of the image?

**Comment by bebraw** [comment]
You can dig it fairly cheaply from exif data if that exists. There is other meta too if I remember right. ImageMagick has certain tooling for that. I have a feeling getting the dimensions isn't a problem here.

**Comment by jhnns** [comment]
Slightly related discussion: https://lists.w3.org/Archives/Public/public-respimg/2016Sep/0008.html

**Comment by benurb** [comment]
Any news on this? Would be a great addition 👍

**Comment by michael-ciniawsky** [comment]
posthtml-loader or a template function (https://github.com/webpack-contrib/html-loader/releases/tag/v1.0.0-alpha.0)
