### ISSUE TITLE
"root" resolution doesn't work with other parsers that use `JSON.stringify`

### ISSUE THREAD

**Issue by chrisnicola** [webpack-contrib/html-loader#95]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.25

**HTML-Loader version:**
0.4.4

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**

When testing out passing template output from the `pug-html-loader` I was unable to pass it to `html-loader` It seems both loaders return an export string with the content passed to `JSON.stringify` however this results in an escaped source string like `\"/logo.svg\"/`. This no longer matches up with the root lookup expansion since it doesn't start with `/` anymore.

**Expected/desired behavior:**

I guess this is possibly a bug, or possible just a question. Should this work with template parsers like `pug`? I was unable to get it working with either `pug-html-loader` or using `apply-loader!pug-loader` as `html-loader` doesn't seem to work with the output of the apply loader either.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
- Setup a template with a root resolved image tag
- Apply loaders like `html?root=images!pug-html`

**What is the motivation / use case for changing the behavior?**
- Better interoperability with template languages which often don't implement html-loader's particularly useful features like image loading.

**Comment by michael-ciniawsky** [comment]
@chrisnicola `pug-html-loader` needs to return the `{String}` without using `JSON.stringify`. Template loaders can leverage `this.loaderIndex`  the return their results (`{String}`, JSON.stringify, `{Function}`, Module) based on the position in the loader chain.
